// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chip_label`, `format_build_time`, `is_dev_build`, `is_dirty`, `tooltip_text`, `unix_to_ymdhm`

/// One-shot read of the bridge's build identity. Cheap — just
/// reads compiled-in `&'static str` constants and formats two
/// strings. Safe to call from app startup.
Future<BuildInfo> readBuildInfo() =>
    RustLib.instance.api.crateApiBuildInfoReadBuildInfo();

/// Single point-in-time view of the bridge binary's build identity.
/// Stable across a process's lifetime, so the Dart side reads it
/// once at startup rather than polling.
class BuildInfo {
  /// `dev` for debug builds, empty for release. The titlebar chip
  /// uses this to decide colour: amber on debug, subtle on release.
  final bool isDev;

  /// True if the working tree had uncommitted changes when
  /// `build.rs` ran. The chip shows red when this is true on a
  /// debug build — the binary contains code that can't be
  /// reproduced from a SHA alone.
  final bool isDirty;

  /// Short git SHA, e.g. `225a501`, or `unknown` if `build.rs`
  /// couldn't shell out to git.
  final String gitSha;

  /// Branch checked out at build time. Used in the tooltip; the
  /// chip itself shows only the SHA.
  final String gitBranch;

  /// One-line chip label, e.g. `dev · 225a501 · dirty` or just
  /// `225a501`. Pre-formatted on the Rust side so the Dart code
  /// stays a thin renderer.
  final String chipLabel;

  /// Single-line tooltip with profile, branch, sha, dirty, and a
  /// human-readable build time, e.g.
  /// `debug · main · 225a501 · built 2026-04-25 14:32 UTC`.
  final String tooltip;

  const BuildInfo({
    required this.isDev,
    required this.isDirty,
    required this.gitSha,
    required this.gitBranch,
    required this.chipLabel,
    required this.tooltip,
  });

  @override
  int get hashCode =>
      isDev.hashCode ^
      isDirty.hashCode ^
      gitSha.hashCode ^
      gitBranch.hashCode ^
      chipLabel.hashCode ^
      tooltip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildInfo &&
          runtimeType == other.runtimeType &&
          isDev == other.isDev &&
          isDirty == other.isDirty &&
          gitSha == other.gitSha &&
          gitBranch == other.gitBranch &&
          chipLabel == other.chipLabel &&
          tooltip == other.tooltip;
}
