// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Spawns the embedded iroh daemon on a dedicated OS thread and
/// registers its `RegistryState` + pair info with the bridge so
/// `LocalSession` and the pair-mobile FRB API can read from them.
/// Idempotent — a second call is a no-op.
Future<void> bootEmbeddedDaemon() =>
    RustLib.instance.api.crateApiEmbeddedDaemonBootEmbeddedDaemon();
