// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Spawns the embedded iroh daemon on a dedicated OS thread and
/// registers its `RegistryState` + pair info with the bridge so the
/// pair-mobile FRB API and the loopback bootstrap can read from
/// them. Idempotent — a second call is a no-op.
Future<void> bootEmbeddedDaemon() =>
    RustLib.instance.api.crateApiEmbeddedDaemonBootEmbeddedDaemon();

/// Keep the Add Agent modal's hidden prewarmed launch aligned with
/// the current section + selected agent. Desktop-only optimisation:
/// the loopback iroh transport still owns the real tab mutation, but
/// this direct bridge call lets the embedded daemon reuse the already
/// launched PTY when the user presses Create.
Future<void> syncAddAgentModalPrewarm({
  required String sectionId,
  String? selectedAgentId,
}) => RustLib.instance.api.crateApiEmbeddedDaemonSyncAddAgentModalPrewarm(
  sectionId: sectionId,
  selectedAgentId: selectedAgentId,
);

/// Cancel the Add Agent modal's currently reserved hidden launch, if
/// any. Called when the modal dismisses without creating a tab so the
/// background PTY does not linger.
Future<void> cancelActiveAddAgentPrewarm() =>
    RustLib.instance.api.crateApiEmbeddedDaemonCancelActiveAddAgentPrewarm();

/// Snapshot of the embedded daemon's iroh address. Returns `None`
/// until [`boot_embedded_daemon`] has finished binding the endpoint
/// (typically a few hundred milliseconds after `boot`).
Future<LoopbackSessionAddr?> loopbackSessionAddr() =>
    RustLib.instance.api.crateApiEmbeddedDaemonLoopbackSessionAddr();

/// Block until the embedded daemon has bound its iroh endpoint and
/// return its loopback address. Polls [`loopback_session_addr`] on
/// the bridge's tokio runtime so the FRB worker thread stays free.
/// Times out after `timeout_ms` (caller-supplied; the Dart bootstrap
/// passes 10 000 ms).
///
/// Errors:
///   * `boot_embedded_daemon` was never called (daemon thread isn't
///     running) — returns the timeout error after the deadline.
///   * The daemon thread is running but its endpoint bind failed —
///     same observable: timeout. The bind error is logged; surfacing
///     it across this FFI would couple the bridge to the
///     `daemon-sandbox` error type.
Future<LoopbackSessionAddr> awaitLoopbackSessionAddr({
  required int timeoutMs,
}) => RustLib.instance.api.crateApiEmbeddedDaemonAwaitLoopbackSessionAddr(
  timeoutMs: timeoutMs,
);

/// Hex-encoded `EndpointId` + direct socket addresses + relay URLs
/// of the running embedded daemon. Drives the desktop's loopback
/// bootstrap: the UI's `DaemonConnection` is an `IrohTransport`
/// dialling this address, exercising the same wire surface mobile
/// uses.
class LoopbackSessionAddr {
  final String endpointId;
  final List<String> directAddrs;
  final List<String> relayUrls;

  const LoopbackSessionAddr({
    required this.endpointId,
    required this.directAddrs,
    required this.relayUrls,
  });

  @override
  int get hashCode =>
      endpointId.hashCode ^ directAddrs.hashCode ^ relayUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoopbackSessionAddr &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          directAddrs == other.directAddrs &&
          relayUrls == other.relayUrls;
}
