// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'iroh_client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'local_session.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `agent_def_to_dto`, `attached_key`, `available_open_in_apps`, `branch_compare_file_to_dto`, `changed_file_to_dto`, `check_to_dto`, `commit_to_dto`, `detach_internal`, `flatten_project_store`, `map_action_access_back`, `map_action_access`, `map_action_icon_back`, `map_action_icon`, `map_action_scope_back`, `map_action_scope`, `map_agent_provider_back`, `map_agent_provider`, `map_project_kind`, `open_in_app_to_dto`, `parse_open_in_app_id`, `parse_toolbar_action_id`, `pr_to_dto`, `project_action_from_dto`, `project_action_to_dto`, `run_changed_file_action`, `submit_direct_task`, `submit_worktree_task`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttachedTab`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Construct a session bound to the desktop's in-process daemon.
Future<LocalSession> localConnect() =>
    RustLib.instance.api.crateApiLocalSessionLocalConnect();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalSession>>
abstract class LocalSession implements RustOpaqueInterface {
  /// Append an agent tab (or plain shell, when `agent_id` is
  /// empty / the Terminal sentinel) to `section_id`'s task and
  /// queue its PTY launch. Mirrors
  /// `desktop/src/add_agent_modal.rs::submit_add_agent_modal`.
  ///
  /// Returns the new tab id so the UI can switch to it.
  /// Empty `agent_id` is treated the same way as GPUI's
  /// `terminal_launch_config_for_selected_agent(None)` —
  /// i.e. opens a plain shell in the section's worktree.
  Future<String> addAgentToSection({
    required String sectionId,
    required String agentId,
  });

  /// Add an existing on-disk project to the embedded daemon's
  /// project store. Returns `Ok(true)` if the project was inserted,
  /// `Ok(false)` if a project at the same path already existed
  /// (idempotent — re-adding is a no-op, not an error).
  ///
  /// Heavy `prepare_project` work runs on a dedicated thread (see
  /// [`another_one_core::project_service::spawn_project_add`]) so
  /// the FRB caller doesn't block. On success, pushes a fresh
  /// `ProjectList` reply so listeners refresh without a follow-up
  /// `list_projects()` round-trip.
  Future<bool> addProject({required String path});

  /// Subscribe to live PTY bytes for `(section_id, tab_id)`.
  ///
  /// Replaces any previous attachment: aborts the previous
  /// forwarder, clears this viewer's entry from the previous
  /// tab's `active_viewers`, then subscribes to the new tab's
  /// broadcast and spawns a forwarder that drains it into
  /// `incoming_tx`. The new viewport size has to be set via
  /// [`Self::tab_resize`] after attach — bytes start flowing
  /// immediately, but no resize is implied.
  ///
  /// Errors if the tab isn't running (no `broadcasts` entry); the
  /// caller should `launch_tab` first.
  Future<void> attachTab({required String sectionId, required String tabId});

  /// Close the session: detaches any attached tab, drops both
  /// channel senders so active subscriptions exit, and clears
  /// per-viewer state on the registry. Idempotent.
  Future<void> close();

  /// Create a new branch from HEAD on `project_id`. When
  /// `use_current_task` is true, switches the current checkout
  /// (no new worktree). Otherwise a new worktree is created
  /// next to the existing project, optionally migrating any
  /// uncommitted changes.
  ///
  /// Returns the new task's `section_id` for the worktree case;
  /// empty string for the current-task case (the caller's UI
  /// just dismisses the modal). Routes
  /// [`another_one_core::project_service::spawn_branch_creation`].
  Future<String> createBranch({
    required String projectId,
    required String branchName,
    required bool useCurrentTask,
    required bool migrateChanges,
  });

  /// Spawn a review task for a pull request — clones into a
  /// worktree at the PR's head branch, prepares the project,
  /// inserts both into the daemon's store, and returns the new
  /// section_id.
  ///
  /// Routes
  /// [`another_one_core::project_service::spawn_review_task_creation`]
  /// and mirrors the `create_worktree_task` pattern. Auto-runs
  /// project actions and the configured agent CLI when
  /// `agent_provider` is set.
  Future<String> createReviewTask({
    required String projectId,
    required BigInt pullRequestNumber,
    required String headBranch,
    AgentProvider? agentProvider,
  });

  /// Create a worktree task on `project_id`. Spawns a fresh git
  /// worktree from `source_branch` (the new branch is named after
  /// the slugified `task_name`), prepares the project, and inserts
  /// both the worktree project and the task into the daemon's
  /// store. Returns the new task's `section_id` so the caller can
  /// navigate to it.
  ///
  /// `agent_provider` is optional; `None` means launch a plain
  /// shell (matches `TerminalLaunchConfig::default()`). When set,
  /// future `launch_tab` calls on the new task's section spawn
  /// the agent CLI with its standard arguments.
  ///
  /// Heavy filesystem work (`create_task_worktree` →
  /// `prepare_project`) runs on a dedicated thread inside
  /// `spawn_task_creation`. We await its broadcast channel reply,
  /// then mutate the registry under one lock.
  Future<String> createWorktreeTask({
    required String projectId,
    required String taskName,
    required String sourceBranch,
    AgentProvider? agentProvider,
  });

  /// Remove one custom action by id from both the project's own
  /// list and `UiState::global_actions` (whichever currently holds
  /// it). Returns `true` if anything was removed.
  Future<bool> deleteProjectAction({
    required String projectId,
    required String actionId,
  });

  /// Stop forwarding PTY bytes for the currently-attached tab.
  /// Idempotent.
  Future<void> detachTab();

  /// Discard one file's changes. Untracked files are deleted; tracked
  /// files are restored from HEAD via `git restore` (with checkout
  /// fallback for older git). Mirrors GPUI's `revert_changed_file`
  /// behaviour: returns success even on no-op, errors only when
  /// every git invocation fails.
  Future<void> discardChangedFile({
    required String projectId,
    required String path,
    String? originalPath,
    required bool untracked,
  });

  /// Fetch open pull requests for `project_id` filtered by
  /// `filter_index` (0=all, 1=needs my review, 2=author:@me,
  /// 3=draft) plus an optional free-text `query`. Powers the
  /// project page's Open PRs section.
  ///
  /// Routes [`another_one_core::git_actions::find_project_pull_requests`]
  /// inside `spawn_blocking` (it shells out to `gh pr list`).
  /// Returns `Ok(None)` for unknown projects; errors propagate
  /// for gh CLI failures (CLI missing, auth, network).
  Future<List<ProjectPagePullRequestDto>?> findProjectPullRequests({
    required String projectId,
    required int filterIndex,
    required String query,
  });

  /// Resolve the latest PullRequest status for `project_id`'s
  /// current branch (open PR's number + url + state). Powers the
  /// titlebar git-actions dropdown's Create PR / Draft PR
  /// enabledness gate.
  ///
  /// Routes [`another_one_core::git_actions::find_latest_pull_request_status`]
  /// inside `spawn_blocking`. Returns `Ok(None)` when the project
  /// is unknown or no PR exists for the branch.
  Future<PullRequestStatusDto?> findPullRequestStatus({
    required String projectId,
  });

  /// Ask the daemon to spawn the given tab's PTY if it isn't
  /// already running. See [`Self`] doc for the launch flow.
  Future<void> launchTab({required String sectionId, required String tabId});

  /// Project actions configured for `project_id` — the merged
  /// list of per-project + global custom actions, in the same
  /// order GPUI's titlebar split-button dropdown renders. Per-
  /// project entries override global ones with the same id (so
  /// "save global copy" can later be undone by deleting the
  /// project entry).
  ///
  /// Returns an empty list when `project_id` is unknown — matches
  /// `ProjectStore::project_actions` behaviour for that case.
  Future<List<ProjectActionDto>> listProjectActions({
    required String projectId,
  });

  /// Push a project list through [`Self::subscribe_worker_replies`].
  ///
  /// Reads from the host-registered [`RegistryState::project_store`]
  /// and flattens it into the bridge's `ProjectSummary` / `TaskSummary` /
  /// `TabSummary` shape. Boot-order forgiving — if the registry
  /// hasn't been registered yet, sends an empty list.
  Future<void> listProjects();

  /// Snapshot of the host's "Open In" configuration: which apps
  /// are enabled (intersection of installed-on-host with the user's
  /// configured set) and which one was last picked as the
  /// preferred default.
  ///
  /// The titlebar split-button uses `preferred_app_id` for its
  /// primary-action icon and `enabled_apps` for the chevron
  /// dropdown. Both are global across projects — `project_id` only
  /// matters when actually launching, not when rendering the
  /// chrome.
  ///
  /// Cheap to call repeatedly: the install detection runs through
  /// `<CurrentPlatform as HeadlessPlatform>::is_open_in_app_available`
  /// (a `$PATH` walk on Linux/Windows, bundle existence on macOS),
  /// and the project store read is a single mutex acquisition.
  Future<OpenInState> openInState();

  /// Open a project's directory in the named app and record it as
  /// the user's preferred default. Mirrors GPUI's
  /// `App::open_project_directory_in_app`: spawn the platform
  /// command, then on success persist `preferred_open_in_app` so
  /// the next titlebar click goes there directly.
  ///
  /// The "spawn first, save preferred only on success" ordering
  /// matches GPUI — a failed spawn doesn't leave the preferred
  /// pointing at a broken target.
  Future<void> openProjectInApp({
    required String projectId,
    required String appId,
  });

  /// Default branch GPUI seeds the new-task modal with for
  /// `project_id`. Wraps `ProjectStore::primary_branch_for_project`
  /// with `prefer_default=true`.
  Future<String?> primaryBranchForProject({required String projectId});

  /// Snapshot the active project's branch metadata: current
  /// branch, ahead/behind counts. Powers the titlebar git-actions
  /// split-button's primary-action selection (Commit when there
  /// are changes, Push when ahead, Pull when behind, Fetch
  /// otherwise — the changes-vs-clean side comes from
  /// `read_changed_files`).
  ///
  /// Reads through `read_project_git_state` with
  /// `include_metadata=true` (so ahead/behind populate) inside
  /// `spawn_blocking`. Returns `Ok(None)` for unknown projects.
  Future<ActiveGitStateDto?> readActiveGitState({required String projectId});

  /// Diff the project's current branch against `target_branch`
  /// (= `target..HEAD`). Powers the right sidebar's Compare pane.
  /// Routes
  /// [`another_one_core::project_store::read_project_branch_compare_state`]
  /// inside `spawn_blocking`.
  ///
  /// Returns `Ok(None)` for unknown projects. Errors propagate
  /// from git when the target branch doesn't exist or the diff
  /// invocation fails.
  Future<BranchCompareView?> readBranchCompareState({
    required String projectId,
    required String targetBranch,
  });

  /// Read the list of files with working-tree changes for
  /// `project_id`, mirroring GPUI's right-sidebar Changes pane
  /// data source. Calls into
  /// [`another_one_core::project_store::read_project_git_state`]
  /// with `include_metadata=false` (the right sidebar doesn't
  /// need branch ahead/behind for this view) inside a
  /// `spawn_blocking` so the FRB caller's tokio runtime stays
  /// free.
  ///
  /// Returns `Ok(None)` when the project id is unknown — UI
  /// renders an empty list rather than surfacing the lookup
  /// failure as an error toast (matches GPUI's "no panel" gate).
  Future<List<ChangedFileDto>?> readChangedFiles({required String projectId});

  /// Per-commit file change list for `project_id` / `commit_id`.
  /// Powers the right-sidebar Commits pane's expandable per-row
  /// file list. Routes
  /// [`another_one_core::project_store::read_project_commit_file_changes`]
  /// inside `spawn_blocking` so the FRB caller's tokio runtime
  /// stays free.
  ///
  /// Returns `Ok(None)` when the project id is unknown — UI shows
  /// the "Couldn't load file changes" empty state in that case.
  /// Errors propagate from git (commit not in tree, etc.).
  Future<List<BranchCompareFileDto>?> readCommitFileChanges({
    required String projectId,
    required String commitId,
  });

  /// Snapshot of agents the user has enabled on this host plus
  /// the id of the one they've picked as default. Drives the
  /// new-task modal's agent multi-select. The returned list is
  /// in the canonical AGENTS order — UI renders it as is.
  Future<EnabledAgentsView> readEnabledAgents();

  /// List of available branches on `project_id`'s git repo.
  /// Wraps `ProjectStore::branch_names`. Powers the new-task
  /// modal's source-branch dropdown.
  ///
  /// Returns an empty list for unknown projects — same
  /// behaviour the core helper has.
  Future<List<String>> readProjectBranches({required String projectId});

  /// Resolve the GitHub remote URL for a project by shelling out to
  /// `git remote get-url origin` and normalising the result through
  /// [`another_one_core::git_actions::find_github_repo_url`].
  /// Returns `None` if the project isn't tracked, has no `origin`
  /// remote, or the remote isn't a github.com URL.
  ///
  /// The blocking git invocation runs in `spawn_blocking` so the
  /// FRB caller's tokio runtime stays free. Dart caches the
  /// result per-project — there's no expectation of liveness if
  /// the user changes the remote at runtime, matching the GPUI
  /// build's "look up once at boot" behaviour
  /// (`spawn_github_link_lookup` in `core::git_service`).
  Future<String?> readProjectGithubUrl({required String projectId});

  /// Pull-request CI checks for `project_id`'s current branch.
  /// Powers the right sidebar's Checks pane. Calls into
  /// [`another_one_core::git_actions::find_pull_request_checks`]
  /// (which shells out to `gh pr checks`) inside `spawn_blocking`.
  ///
  /// Three-state return:
  ///   * `Ok(Some(list))` — the PR exists and these are its checks
  ///     (may be empty when no checks are configured).
  ///   * `Ok(None)` — no PR for the current branch, or the project
  ///     id is unknown. UI shows the empty state.
  ///   * `Err(_)` — gh CLI missing, network failure, or any other
  ///     hard error. UI surfaces the message.
  Future<List<CheckDto>?> readPullRequestChecks({required String projectId});

  /// Recent commits on `project_id`'s current branch, capped at
  /// `limit` entries. Powers the right sidebar's Commits pane —
  /// reads through
  /// [`another_one_core::project_store::read_project_branch_commit_state`]
  /// inside `spawn_blocking` so the FRB caller's tokio runtime
  /// stays free.
  ///
  /// `limit` mirrors GPUI's `commit_page_size_for_project` — the
  /// caller picks the page size; here we don't enforce a default
  /// so the UI can choose. Returns `Ok(None)` for unknown
  /// projects (UI shows the empty state instead of an error).
  Future<RecentCommitsView?> readRecentCommits({
    required String projectId,
    required int limit,
  });

  /// Remove a project from the embedded daemon's store. Cascades
  /// to the project's tasks + terminal sections (see
  /// [`another_one_core::project_store::ProjectStore::remove_project`]).
  /// Idempotent — passing an unknown id is silently a no-op.
  /// Pushes a fresh `ProjectList` reply on completion so
  /// subscribers refresh.
  Future<void> removeProject({required String projectId});

  /// Remove a task (and its terminal sections) from the embedded
  /// daemon's store. The on-disk worktree branch is left
  /// untouched — the GPUI side has the same semantics. Returns
  /// `Ok(true)` if a task was removed, `Ok(false)` for an unknown
  /// id (idempotent).
  Future<bool> removeTask({required String projectId, required String taskId});

  /// Rename a task. Empty / whitespace-only names are rejected so
  /// the daemon never persists a blank label. Returns whether
  /// anything was actually written (an unknown id or a no-op
  /// rename returns `Ok(false)`). Pushes a fresh `ProjectList`
  /// reply on success so the sidebar redraws.
  Future<bool> renameTask({required String taskId, required String newName});

  /// User's preferred default commit action for the active
  /// project's root repo (`"commit"` or `"commit-and-push"`).
  /// `None` when no preference has been recorded — UI defaults to
  /// `"commit"` in that case, matching GPUI's
  /// `resolve_idle_primary_git_action` fallback.
  Future<String?> repoDefaultCommitAction({required String projectId});

  /// Snapshot the resolved branch settings for `project_id` —
  /// configured + effective values for default and target branch
  /// plus the available branch list for the dropdown.
  /// Returns `Ok(None)` when the project is unknown or has no
  /// repo metadata yet.
  Future<ResolvedProjectBranchSettingsDto?> resolvedBranchSettings({
    required String projectId,
  });

  /// Run one custom action inside `section_id`'s task.
  ///
  /// Mirrors `desktop/src/app.rs::run_project_action_in_section`:
  /// builds the launch config (shell or agent kind), appends a
  /// fresh `PersistedTerminalTab` to the section, sets it as the
  /// active tab, queues a `TabLaunchRequest` for the daemon's
  /// drain to spawn, and (for shell actions) records `command\n`
  /// in `pending_post_launch_input` so the drain writes it once
  /// the PTY is up.
  ///
  /// Note (2026-04-25): the bridge's `embedded_daemon` does not
  /// drain `pending_tab_launches` yet (tracked as `another-one-v0k`).
  /// Every other call site already queues there; once the drain
  /// lands, custom-action shell runs come up end-to-end. Until
  /// then this verb commits the tab to the persistent store and
  /// queues — visually correct, but no PTY spawns.
  ///
  /// Returns the new tab id so the caller can switch to it.
  Future<String> runProjectAction({
    required String projectId,
    required String sectionId,
    required String actionId,
  });

  /// Run a toolbar git action (Commit, Push, Pull, etc.) against
  /// `project_id`. Routes
  /// [`another_one_core::git_actions::execute_toolbar_git_action`]
  /// via spawn_blocking.
  ///
  /// `action_id` is one of: `"commit"`, `"commit-and-push"`,
  /// `"undo-last-commit"`, `"fetch"`, `"pull"`, `"push"`,
  /// `"force-push"`, `"create-pr"`, `"create-draft-pr"`. Other
  /// values error.
  ///
  /// Returns the toast message + warning/refresh flags so the UI
  /// can surface a snackbar and decide whether to invalidate
  /// changedFilesProvider / activeGitStateProvider.
  Future<ToolbarActionOutcomeDto> runToolbarGitAction({
    required String projectId,
    required String actionId,
  });

  /// Insert or update one custom action.
  ///
  /// `save_global_copy=true` saves to `UiState::global_actions`
  /// (visible across every project on this host) and removes any
  /// per-project copy with the same id. `false` saves to the
  /// project's own `actions` list and removes any global copy with
  /// the same id. Mirrors `ProjectStore::upsert_project_action`.
  ///
  /// `dto.id` may be empty when editing a brand-new action — the
  /// bridge generates a uuid in that case so callers don't have to
  /// reach for `uuid` from Dart.
  Future<void> saveProjectAction({
    required String projectId,
    required ProjectActionDto action,
    required bool saveGlobalCopy,
  });

  /// Send raw PTY stdin bytes to the currently-attached tab.
  ///
  /// Looks up the tab's writer in `RegistryState::writers` and
  /// writes synchronously. Errors if no tab is attached or the
  /// writer has been dropped (tab exited / runtime gone).
  Future<void> send({required List<int> bytes});

  /// Update the configured default branch or default-target branch
  /// for `project_id`'s root project. `field` must be one of
  /// `"default-branch"` or `"default-target-branch"`. `branch_name`
  /// of `None` clears the configured override (resolved-effective
  /// goes back to automatic).
  ///
  /// Returns `Ok(true)` when the persisted store changed,
  /// `Ok(false)` for a no-op re-set. Errors when the branch isn't
  /// in the available list (matches GPUI's validation), or when
  /// the project lookup fails.
  Future<bool> setProjectBranchSetting({
    required String projectId,
    required String field,
    String? branchName,
  });

  /// Pin or unpin a task. Pinned tasks float to the top of their
  /// project's task list (mirrors `child_entries.sort_by_key(!is_pinned)`
  /// in the GPUI sidebar). Returns whether the pin state actually
  /// changed; an idempotent re-set is `Ok(false)`. Pushes a fresh
  /// `ProjectList` reply on every call so the sort updates
  /// immediately.
  Future<bool> setTaskPinned({required String taskId, required bool pinned});

  /// Compute the canonical branch slug for a free-text input.
  /// Mirrors GPUI's live preview that updates beneath the
  /// branch-name input. Routes
  /// [`another_one_core::project_store::slugify_branch_name`].
  /// Takes `&self` only so FRB binds it as an instance method
  /// on `LocalSession` — it doesn't actually read session state.
  Future<String> slugifyBranchName({required String name});

  /// `git add -A` on the project root — stage every change.
  Future<void> stageAllChanges({required String projectId});

  /// Stage one changed file via `git add -A -- <path>`. `original_path`
  /// is set only for renames/copies — the helper passes both
  /// arguments so git can resolve the rename pair correctly.
  /// Errors bubble up as anyhow with the git stderr appended,
  /// matching what GPUI shows in toasts.
  Future<void> stageChangedFile({
    required String projectId,
    required String path,
    String? originalPath,
  });

  /// Submit the new-task modal: spawns a worktree task or a
  /// direct-mode task depending on `worktree_mode`. Mirrors
  /// `desktop/src/app.rs::submit_new_task_modal` +
  /// `launch_task_request`.
  ///
  /// `agent_ids` is the new-task modal's multi-select picks; the
  /// resulting `TerminalLaunchConfig` is built via
  /// `terminal_launch_config_for_selected_agents` (so an empty
  /// set + a `Shell` sentinel pass through to a default
  /// `TerminalLaunchConfig` exactly the same way GPUI does).
  ///
  /// `branch_mode_existing=true` reuses an existing branch in
  /// the worktree path; `false` cuts a new branch from
  /// `source_branch`. Ignored when `worktree_mode=false`
  /// (Direct mode always uses the project's current branch).
  ///
  /// Returns the new task's section_id so the UI can navigate.
  Future<String> submitNewTask({
    required String projectId,
    required String taskName,
    required String sourceBranch,
    required List<String> agentIds,
    required bool branchModeExisting,
    required bool worktreeMode,
  });

  /// Stream PTY bytes for the attached tab into a Dart sink.
  /// One-shot subscription; the second call returns
  /// "already subscribed".
  Stream<Uint8List> subscribe();

  /// Stream worker replies into a Dart sink. One-shot.
  Stream<WorkerReply> subscribeWorkerReplies();

  /// Resize the currently-attached tab's PTY.
  ///
  /// Updates this viewer's entry in `RegistryState::active_viewers`
  /// and asks the registry to recompute the effective
  /// (min-across-viewers) size. The desktop UI render tick drains
  /// the resulting `pending_resizes` queue.
  Future<void> tabResize({required int cols, required int rows});

  /// Unstage every currently-staged change.
  Future<void> unstageAllChanges({required String projectId});

  /// Unstage one changed file via `git restore --staged -- <path>`,
  /// falling back to `git reset HEAD -- <path>` if the repo is
  /// pre-2.23 (matches `core::unstage_changed_file`).
  Future<void> unstageChangedFile({
    required String projectId,
    required String path,
    String? originalPath,
  });
}

/// Branch metadata snapshot for the active project — current branch
/// name plus ahead/behind counts. Drives the titlebar's
/// idle-primary-action selection.
class ActiveGitStateDto {
  final String? currentBranch;
  final int aheadCount;
  final int behindCount;

  const ActiveGitStateDto({
    this.currentBranch,
    required this.aheadCount,
    required this.behindCount,
  });

  @override
  int get hashCode =>
      currentBranch.hashCode ^ aheadCount.hashCode ^ behindCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveGitStateDto &&
          runtimeType == other.runtimeType &&
          currentBranch == other.currentBranch &&
          aheadCount == other.aheadCount &&
          behindCount == other.behindCount;
}

/// FRB-friendly mirror of one entry in
/// [`another_one_core::agents::AGENTS`]. Carries everything the
/// new-task modal's agent multi-select needs to render a chip
/// (label + icon path) without the UI side hard-coding a copy.
class AgentSummaryDto {
  /// Stable id used by the bridge's `submit_new_task` verb.
  final String id;
  final String label;
  final String iconPath;
  final AgentProvider? provider;

  const AgentSummaryDto({
    required this.id,
    required this.label,
    required this.iconPath,
    this.provider,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ iconPath.hashCode ^ provider.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          iconPath == other.iconPath &&
          provider == other.provider;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::BranchCompareFile`]. Each
/// entry is one file changed inside a commit (or branch compare).
/// `status` is the single git status char ('A', 'M', 'D', 'R', 'C',
/// 'T') passed through verbatim — UI maps it via the same
/// `changed_file_status_color` table the Changes pane uses.
class BranchCompareFileDto {
  final String path;

  /// Set on rename/copy entries — the from-path. UI renders
  /// "Renamed from {original_path}" beneath the row when present.
  final String? originalPath;

  /// Single status char as a 1-char string (FRB doesn't expose
  /// `char` directly).
  final String status;
  final int additions;
  final int deletions;

  const BranchCompareFileDto({
    required this.path,
    this.originalPath,
    required this.status,
    required this.additions,
    required this.deletions,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      originalPath.hashCode ^
      status.hashCode ^
      additions.hashCode ^
      deletions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BranchCompareFileDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          originalPath == other.originalPath &&
          status == other.status &&
          additions == other.additions &&
          deletions == other.deletions;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::ProjectBranchCompareState`].
/// Drives the right sidebar's Compare pane: the current branch +
/// configured target + the file list of the diff.
class BranchCompareView {
  final String? currentBranch;
  final String targetBranch;
  final List<BranchCompareFileDto> files;

  const BranchCompareView({
    this.currentBranch,
    required this.targetBranch,
    required this.files,
  });

  @override
  int get hashCode =>
      currentBranch.hashCode ^ targetBranch.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BranchCompareView &&
          runtimeType == other.runtimeType &&
          currentBranch == other.currentBranch &&
          targetBranch == other.targetBranch &&
          files == other.files;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::ChangedFile`]. Carries the
/// raw status chars + diff counts; UI maps them to glyphs/colours
/// per `desktop/src/right_sidebar.rs::changed_file_status_char`
/// and `changed_file_status_color`. We don't pre-format on the
/// Rust side so the bridge stays display-agnostic and we don't
/// pay the cross-FFI cost of re-encoding every redraw.
class ChangedFileDto {
  /// Path relative to the project root, the way `git status` reports it.
  final String path;

  /// Set on rename (`R`) / copy (`C`) entries — the from-path. UI
  /// renders this as `original → path` when present.
  final String? originalPath;
  final int stagedAdditions;
  final int stagedDeletions;
  final int unstagedAdditions;
  final int unstagedDeletions;

  /// Index status char from `git status --porcelain` — `M`/`A`/`D`/
  /// `R`/`C`/`?`/' '. UI maps via the GPUI char-to-glyph table.
  final String indexStatus;

  /// Worktree status char — same alphabet as `index_status`.
  final String worktreeStatus;

  /// True when the file is `??` (untracked) in `git status`.
  final bool untracked;

  const ChangedFileDto({
    required this.path,
    this.originalPath,
    required this.stagedAdditions,
    required this.stagedDeletions,
    required this.unstagedAdditions,
    required this.unstagedDeletions,
    required this.indexStatus,
    required this.worktreeStatus,
    required this.untracked,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      originalPath.hashCode ^
      stagedAdditions.hashCode ^
      stagedDeletions.hashCode ^
      unstagedAdditions.hashCode ^
      unstagedDeletions.hashCode ^
      indexStatus.hashCode ^
      worktreeStatus.hashCode ^
      untracked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangedFileDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          originalPath == other.originalPath &&
          stagedAdditions == other.stagedAdditions &&
          stagedDeletions == other.stagedDeletions &&
          unstagedAdditions == other.unstagedAdditions &&
          unstagedDeletions == other.unstagedDeletions &&
          indexStatus == other.indexStatus &&
          worktreeStatus == other.worktreeStatus &&
          untracked == other.untracked;
}

/// FRB-friendly mirror of
/// [`another_one_core::git_actions::PullRequestCheckBucket`].
/// Drives the glyph + colour for each check row on the right
/// sidebar's Checks pane.
enum CheckBucket { pass, fail, pending, skipping, cancel }

/// FRB-friendly mirror of
/// [`another_one_core::git_actions::PullRequestCheck`]. Mostly raw
/// — UI maps `bucket` to glyph/colour and `state` is the verbatim
/// string `gh pr checks` returned ("pass", "in_progress", etc.).
class CheckDto {
  /// Check name (e.g. "build / linux", "lint").
  final String name;

  /// Raw state string from gh CLI; shown as the row subtitle.
  final String state;
  final CheckBucket bucket;

  /// Optional human description gh CLI sometimes provides.
  final String? description;

  /// Link to the check run page on GitHub. UI renders the row
  /// clickable when set.
  final String? link;

  /// Pre-formatted "1m 23s"-style duration. None for checks that
  /// haven't started or completed.
  final String? durationText;

  const CheckDto({
    required this.name,
    required this.state,
    required this.bucket,
    this.description,
    this.link,
    this.durationText,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      state.hashCode ^
      bucket.hashCode ^
      description.hashCode ^
      link.hashCode ^
      durationText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          state == other.state &&
          bucket == other.bucket &&
          description == other.description &&
          link == other.link &&
          durationText == other.durationText;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::BranchCommit`]. Carries the
/// pre-computed relative authored timestamp ("3 hours ago") so the
/// UI doesn't have to round-trip through chrono on every redraw.
class CommitDto {
  /// Full SHA — used as the row id and for the diff lookup.
  final String id;

  /// 7-char abbreviated SHA shown next to the message.
  final String shortId;

  /// First line of the commit message.
  final String subject;
  final String authorName;

  /// Pre-formatted "X minutes ago"-style label. Computed Rust-side
  /// because chrono is already a dep there; doing it Dart-side
  /// would mean shipping a humanize-duration package for one
  /// caller. This is borderline display logic but the read is
  /// one-shot per pane open so the FFI cost is a wash.
  final String authoredRelative;

  const CommitDto({
    required this.id,
    required this.shortId,
    required this.subject,
    required this.authorName,
    required this.authoredRelative,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      shortId.hashCode ^
      subject.hashCode ^
      authorName.hashCode ^
      authoredRelative.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          shortId == other.shortId &&
          subject == other.subject &&
          authorName == other.authorName &&
          authoredRelative == other.authoredRelative;
}

/// Snapshot returned by [`LocalSession::read_enabled_agents`].
/// Pairs the enabled-agents list with the user's preferred default
/// (the chip the modal pre-checks on open).
class EnabledAgentsView {
  final List<AgentSummaryDto> agents;
  final String? defaultAgentId;

  const EnabledAgentsView({required this.agents, this.defaultAgentId});

  @override
  int get hashCode => agents.hashCode ^ defaultAgentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnabledAgentsView &&
          runtimeType == other.runtimeType &&
          agents == other.agents &&
          defaultAgentId == other.defaultAgentId;
}

/// FRB-friendly mirror of [`OpenInAppKind`] with the
/// pre-computed display strings. Lives here (not in core) because
/// FRB's binding generator only walks bridge crate types — we'd
/// need a re-export shim either way and the mapping is one-to-one.
class OpenInAppDto {
  /// Stable id matching `OpenInAppKind::id()` — `"cursor"`,
  /// `"zed"`, `"vscode"`, `"file-manager"`. Round-trips through
  /// [`LocalSession::open_project_in_app`].
  final String id;

  /// Human-readable label rendered in the dropdown. Localised at
  /// the platform level (Finder vs File Manager vs File Explorer).
  final String label;

  /// Tooltip text — same copy GPUI's titlebar dropdown uses.
  final String description;

  /// Asset path for the app's glyph, relative to the app bundle's
  /// asset root. Both the GPUI and Flutter UIs ship the same
  /// `assets/icons/open_in__*.svg` files, so the path is valid
  /// on either side without translation.
  final String iconPath;

  const OpenInAppDto({
    required this.id,
    required this.label,
    required this.description,
    required this.iconPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ description.hashCode ^ iconPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenInAppDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          description == other.description &&
          iconPath == other.iconPath;
}

/// Snapshot returned by [`LocalSession::open_in_state`].
class OpenInState {
  /// Apps offered in the dropdown, ordered as `OpenInAppKind::all()`
  /// declares them — Cursor, Zed, VS Code, File Manager.
  final List<OpenInAppDto> enabledApps;

  /// Id of the app the titlebar's primary action launches. `None`
  /// when no app is enabled at all (a fresh install on a host with
  /// none of the editors detected).
  final String? preferredAppId;

  const OpenInState({required this.enabledApps, this.preferredAppId});

  @override
  int get hashCode => enabledApps.hashCode ^ preferredAppId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenInState &&
          runtimeType == other.runtimeType &&
          enabledApps == other.enabledApps &&
          preferredAppId == other.preferredAppId;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::ProjectActionAccess`]. Drives
/// the agent-mode CLI's permission flag — `default` passes nothing
/// extra, the other three map to `--read-only`, `--workspace-write`,
/// `--full-access` (Claude Code today; other providers ignore).
enum ProjectActionAccessDto { default_, readOnly, workspaceWrite, fullAccess }

/// FRB-friendly mirror of
/// [`another_one_core::project_store::ProjectAction`]. Carries the
/// lot — id (empty for a never-saved action), display name, icon,
/// run-on-worktree-create flag, scope, and the kind-specific
/// payload. UI maps `icon` to its asset path via
/// `ProjectActionIconDto.icon_path` (Dart-side helper).
class ProjectActionDto {
  final String id;
  final String name;
  final ProjectActionIconDto icon;
  final bool runOnWorktreeCreate;
  final ProjectActionScopeDto scope;
  final ProjectActionKindDto kind;

  const ProjectActionDto({
    required this.id,
    required this.name,
    required this.icon,
    required this.runOnWorktreeCreate,
    required this.scope,
    required this.kind,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      icon.hashCode ^
      runOnWorktreeCreate.hashCode ^
      scope.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectActionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          icon == other.icon &&
          runOnWorktreeCreate == other.runOnWorktreeCreate &&
          scope == other.scope &&
          kind == other.kind;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::ProjectActionIcon`]. Stable
/// kebab-case ids round-trip the GPUI on-disk format
/// (`projects.json`) so a user can switch desktop binaries without
/// the icon picker resetting.
enum ProjectActionIconDto { play, test, lint, configure, build, debug, agent }

@freezed
sealed class ProjectActionKindDto with _$ProjectActionKindDto {
  const ProjectActionKindDto._();

  /// A shell command typed verbatim into a freshly-spawned PTY.
  /// `command` is run as `<command>\n` so multi-line input works
  /// the same way it would in an interactive shell.
  const factory ProjectActionKindDto.shell({required String command}) =
      ProjectActionKindDto_Shell;

  /// An agent CLI launch. `prompt` is the seed message;
  /// `model`/`traits`/`mode`/`access` are agent-specific knobs
  /// fed to `project_action_agent_launch_args`.
  const factory ProjectActionKindDto.agent({
    required String prompt,
    required AgentProvider provider,
    String? model,
    String? traits,
    String? mode,
    required ProjectActionAccessDto access,
  }) = ProjectActionKindDto_Agent;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::ProjectActionScope`]. Ordered
/// "project first, global last" because that's how the dropdown row
/// order treats them — global rows render with a globe glyph beside
/// the action label.
enum ProjectActionScopeDto { project, global }

/// FRB-friendly mirror of
/// [`another_one_core::git_actions::ProjectPagePullRequest`]. One
/// entry per row in the project page's Open PRs section.
class ProjectPagePullRequestDto {
  final BigInt number;
  final String url;
  final String title;

  /// Head ref (the PR's source branch). Rendered in mono on the
  /// row's bottom line.
  final String branch;
  final String author;
  final int linesAdded;
  final int linesRemoved;
  final bool draft;

  /// `true` when GitHub's review_decision is REVIEW_REQUIRED —
  /// drives the red CI badge and 'Review required' chip.
  final bool reviewRequired;
  final bool reviewRequestedToMe;
  final bool createdByMe;
  final PullRequestStateDto state;

  const ProjectPagePullRequestDto({
    required this.number,
    required this.url,
    required this.title,
    required this.branch,
    required this.author,
    required this.linesAdded,
    required this.linesRemoved,
    required this.draft,
    required this.reviewRequired,
    required this.reviewRequestedToMe,
    required this.createdByMe,
    required this.state,
  });

  @override
  int get hashCode =>
      number.hashCode ^
      url.hashCode ^
      title.hashCode ^
      branch.hashCode ^
      author.hashCode ^
      linesAdded.hashCode ^
      linesRemoved.hashCode ^
      draft.hashCode ^
      reviewRequired.hashCode ^
      reviewRequestedToMe.hashCode ^
      createdByMe.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectPagePullRequestDto &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          url == other.url &&
          title == other.title &&
          branch == other.branch &&
          author == other.author &&
          linesAdded == other.linesAdded &&
          linesRemoved == other.linesRemoved &&
          draft == other.draft &&
          reviewRequired == other.reviewRequired &&
          reviewRequestedToMe == other.reviewRequestedToMe &&
          createdByMe == other.createdByMe &&
          state == other.state;
}

/// FRB-friendly mirror of
/// [`another_one_core::git_actions::PullRequestState`]. Drives the
/// chip + chrome on each PR row: open vs merged vs closed shapes
/// the badge palette and the row-level affordances.
enum PullRequestStateDto { open, closed, merged }

/// FRB-friendly mirror of
/// [`another_one_core::git_actions::PullRequestStatus`]. Drives
/// the titlebar dropdown's Create PR / Draft PR enabledness — when
/// a PR already exists for the branch, those rows are disabled.
class PullRequestStatusDto {
  final BigInt number;
  final String url;
  final PullRequestStateDto state;

  const PullRequestStatusDto({
    required this.number,
    required this.url,
    required this.state,
  });

  @override
  int get hashCode => number.hashCode ^ url.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PullRequestStatusDto &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          url == other.url &&
          state == other.state;
}

/// FRB-friendly snapshot of the right sidebar's Commits pane data.
class RecentCommitsView {
  /// Current branch — shown as the pane subtitle in GPUI.
  final String? currentBranch;

  /// True when more commits exist past the requested `limit`. UI
  /// uses this to render a "Load more" affordance.
  final bool hasMore;
  final List<CommitDto> commits;

  const RecentCommitsView({
    this.currentBranch,
    required this.hasMore,
    required this.commits,
  });

  @override
  int get hashCode =>
      currentBranch.hashCode ^ hasMore.hashCode ^ commits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecentCommitsView &&
          runtimeType == other.runtimeType &&
          currentBranch == other.currentBranch &&
          hasMore == other.hasMore &&
          commits == other.commits;
}

/// FRB-friendly mirror of
/// [`another_one_core::project_store::ResolvedProjectBranchSettings`].
/// Drives the project page Configuration panel: the current
/// configured + effective values for both fields, plus the
/// available branch list the dropdowns enumerate.
class ResolvedProjectBranchSettingsDto {
  final String rootProjectId;
  final List<String> availableBranches;

  /// `Some(name)` when the user explicitly picked a default branch;
  /// `None` means automatic (UI shows the trigger label as
  /// "Automatic").
  final String? configuredDefaultBranch;

  /// What the project actually uses today — falls back to
  /// `automatic_primary_branch_name` when configured is None or
  /// unavailable.
  final String? effectiveDefaultBranch;
  final String? configuredDefaultTargetBranch;
  final String? effectiveDefaultTargetBranch;

  const ResolvedProjectBranchSettingsDto({
    required this.rootProjectId,
    required this.availableBranches,
    this.configuredDefaultBranch,
    this.effectiveDefaultBranch,
    this.configuredDefaultTargetBranch,
    this.effectiveDefaultTargetBranch,
  });

  @override
  int get hashCode =>
      rootProjectId.hashCode ^
      availableBranches.hashCode ^
      configuredDefaultBranch.hashCode ^
      effectiveDefaultBranch.hashCode ^
      configuredDefaultTargetBranch.hashCode ^
      effectiveDefaultTargetBranch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedProjectBranchSettingsDto &&
          runtimeType == other.runtimeType &&
          rootProjectId == other.rootProjectId &&
          availableBranches == other.availableBranches &&
          configuredDefaultBranch == other.configuredDefaultBranch &&
          effectiveDefaultBranch == other.effectiveDefaultBranch &&
          configuredDefaultTargetBranch ==
              other.configuredDefaultTargetBranch &&
          effectiveDefaultTargetBranch == other.effectiveDefaultTargetBranch;
}

/// FRB-friendly mirror of
/// [`another_one_core::git_actions::ToolbarActionOutcome`]. The
/// titlebar surfaces `toast_message` as a snackbar (warning palette
/// when `warning` is true) and uses `refresh_git_state` to decide
/// whether to invalidate the active changed-files / git-state
/// providers after the call returns.
class ToolbarActionOutcomeDto {
  final String toastMessage;
  final bool warning;
  final bool refreshGitState;

  const ToolbarActionOutcomeDto({
    required this.toastMessage,
    required this.warning,
    required this.refreshGitState,
  });

  @override
  int get hashCode =>
      toastMessage.hashCode ^ warning.hashCode ^ refreshGitState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolbarActionOutcomeDto &&
          runtimeType == other.runtimeType &&
          toastMessage == other.toastMessage &&
          warning == other.warning &&
          refreshGitState == other.refreshGitState;
}
