// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'iroh_client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attached_key`, `detach_internal`, `flatten_project_store`, `map_agent_provider`, `map_project_kind`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttachedTab`

/// Construct a session bound to the desktop's in-process daemon.
Future<LocalSession> localConnect() =>
    RustLib.instance.api.crateApiLocalSessionLocalConnect();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalSession>>
abstract class LocalSession implements RustOpaqueInterface {
  /// Subscribe to live PTY bytes for `(section_id, tab_id)`.
  ///
  /// Replaces any previous attachment: aborts the previous
  /// forwarder, clears this viewer's entry from the previous
  /// tab's `active_viewers`, then subscribes to the new tab's
  /// broadcast and spawns a forwarder that drains it into
  /// `incoming_tx`. The new viewport size has to be set via
  /// [`Self::tab_resize`] after attach — bytes start flowing
  /// immediately, but no resize is implied.
  ///
  /// Errors if the tab isn't running (no `broadcasts` entry); the
  /// caller should `launch_tab` first.
  Future<void> attachTab({required String sectionId, required String tabId});

  /// Close the session: detaches any attached tab, drops both
  /// channel senders so active subscriptions exit, and clears
  /// per-viewer state on the registry. Idempotent.
  Future<void> close();

  /// Stop forwarding PTY bytes for the currently-attached tab.
  /// Idempotent.
  Future<void> detachTab();

  /// Ask the daemon to spawn the given tab's PTY if it isn't
  /// already running. See [`Self`] doc for the launch flow.
  Future<void> launchTab({required String sectionId, required String tabId});

  /// Push a project list through [`Self::subscribe_worker_replies`].
  ///
  /// Reads from the host-registered [`RegistryState::project_store`]
  /// and flattens it into the bridge's `ProjectSummary` / `TaskSummary` /
  /// `TabSummary` shape. Boot-order forgiving — if the registry
  /// hasn't been registered yet, sends an empty list.
  Future<void> listProjects();

  /// Send raw PTY stdin bytes to the currently-attached tab.
  ///
  /// Looks up the tab's writer in `RegistryState::writers` and
  /// writes synchronously. Errors if no tab is attached or the
  /// writer has been dropped (tab exited / runtime gone).
  Future<void> send({required List<int> bytes});

  /// Stream PTY bytes for the attached tab into a Dart sink.
  /// One-shot subscription; the second call returns
  /// "already subscribed".
  Stream<Uint8List> subscribe();

  /// Stream worker replies into a Dart sink. One-shot.
  Stream<WorkerReply> subscribeWorkerReplies();

  /// Resize the currently-attached tab's PTY.
  ///
  /// Updates this viewer's entry in `RegistryState::active_viewers`
  /// and asks the registry to recompute the effective
  /// (min-across-viewers) size. The desktop UI render tick drains
  /// the resulting `pending_resizes` queue.
  Future<void> tabResize({required int cols, required int rows});
}
