// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `reset_persisted_pairings`, `rewrite_paired_peers_with_local_device`

/// Current pairing material, or `None` if the host hasn't registered
/// the embedded daemon yet (boot race, or the binary was built
/// without daemon-sandbox).
Future<PairingInfo?> pairingInfo() =>
    RustLib.instance.api.crateApiPairPairingInfo();

/// Reset paired mobile access by revoking persisted peers, while
/// preserving the desktop's own loopback self-trust entry, then roll
/// a fresh TOFU nonce and rebuild the pairing URL + QR. Errors
/// surface as a string so the bridge doesn't need to expose a
/// project-wide error type to Dart.
Future<void> regenerateLocalPairing() =>
    RustLib.instance.api.crateApiPairRegenerateLocalPairing();

/// Snapshot of the embedded daemon's current pairing material.
/// Stable for one render of the pair-mobile modal; refetch after
/// [`regenerate_local_pairing`] to pick up the rotated nonce.
class PairingInfo {
  final String url;
  final Uint8List qrPngBytes;

  const PairingInfo({required this.url, required this.qrPngBytes});

  @override
  int get hashCode => url.hashCode ^ qrPngBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          qrPngBytes == other.qrPngBytes;
}
