// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One-shot sample of the host UI's own CPU + memory. Returns
/// zeros for `cpu_time_ns` / `memory_bytes` if the platform
/// sampler returned nothing for our pid (Windows path today).
Future<ResourceSample> readAppResourceSample() =>
    RustLib.instance.api.crateApiResourcesReadAppResourceSample();

/// Single point-in-time resource snapshot.
class ResourceSample {
  /// Wall-clock millis since the unix epoch — used to compute the
  /// elapsed denominator in CPU%.
  final BigInt timestampMs;

  /// Cumulative CPU time the host UI process has consumed in
  /// nanoseconds. Take the delta between two samples to get CPU%.
  final BigInt cpuTimeNs;

  /// Resident set size at this instant (bytes).
  final BigInt memoryBytes;

  /// Total system memory if the platform can report it. Linux/macOS
  /// fill this; Windows currently returns `None` (matches the
  /// GPUI desktop's "hide the total when missing" behaviour).
  final BigInt? totalMemoryBytes;

  const ResourceSample({
    required this.timestampMs,
    required this.cpuTimeNs,
    required this.memoryBytes,
    this.totalMemoryBytes,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      cpuTimeNs.hashCode ^
      memoryBytes.hashCode ^
      totalMemoryBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceSample &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          cpuTimeNs == other.cpuTimeNs &&
          memoryBytes == other.memoryBytes &&
          totalMemoryBytes == other.totalMemoryBytes;
}
