// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `project_to_dto`, `session_to_dto`, `snapshot_to_dto`, `task_to_dto`

/// Hierarchical resource snapshot — host UI process + every tracked
/// PTY child grouped by project → task → session, sorted descending
/// by memory then CPU then label (matching the GPUI desktop's
/// `ResourceIndicator`). Returns `None` if the embedded daemon
/// hasn't booted yet — the popover renders the empty-state pill in
/// that case.
Future<ResourceUsageSnapshotDto?> readResourceUsageSnapshot() =>
    RustLib.instance.api.crateApiResourcesReadResourceUsageSnapshot();

/// One-shot sample of the host UI's own CPU + memory. Returns
/// zeros for `cpu_time_ns` / `memory_bytes` if the platform
/// sampler returned nothing for our pid (Windows path today).
Future<ResourceSample> readAppResourceSample() =>
    RustLib.instance.api.crateApiResourcesReadAppResourceSample();

/// Single point-in-time resource snapshot.
class ResourceSample {
  /// Wall-clock millis since the unix epoch — used to compute the
  /// elapsed denominator in CPU%.
  final BigInt timestampMs;

  /// Cumulative CPU time the host UI process has consumed in
  /// nanoseconds. Take the delta between two samples to get CPU%.
  final BigInt cpuTimeNs;

  /// Resident set size at this instant (bytes).
  final BigInt memoryBytes;

  /// Total system memory if the platform can report it. Linux/macOS
  /// fill this; Windows currently returns `None` (matches the
  /// GPUI desktop's "hide the total when missing" behaviour).
  final BigInt? totalMemoryBytes;

  const ResourceSample({
    required this.timestampMs,
    required this.cpuTimeNs,
    required this.memoryBytes,
    this.totalMemoryBytes,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      cpuTimeNs.hashCode ^
      memoryBytes.hashCode ^
      totalMemoryBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceSample &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          cpuTimeNs == other.cpuTimeNs &&
          memoryBytes == other.memoryBytes &&
          totalMemoryBytes == other.totalMemoryBytes;
}

class ResourceUsageProjectDto {
  final String key;
  final String label;
  final double cpuPercent;
  final BigInt memoryBytes;
  final List<ResourceUsageTaskDto> tasks;

  const ResourceUsageProjectDto({
    required this.key,
    required this.label,
    required this.cpuPercent,
    required this.memoryBytes,
    required this.tasks,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      cpuPercent.hashCode ^
      memoryBytes.hashCode ^
      tasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceUsageProjectDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          cpuPercent == other.cpuPercent &&
          memoryBytes == other.memoryBytes &&
          tasks == other.tasks;
}

class ResourceUsageSessionDto {
  final String key;
  final String label;
  final String iconPath;
  final double cpuPercent;
  final BigInt memoryBytes;

  const ResourceUsageSessionDto({
    required this.key,
    required this.label,
    required this.iconPath,
    required this.cpuPercent,
    required this.memoryBytes,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      iconPath.hashCode ^
      cpuPercent.hashCode ^
      memoryBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceUsageSessionDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          iconPath == other.iconPath &&
          cpuPercent == other.cpuPercent &&
          memoryBytes == other.memoryBytes;
}

/// FRB-exposed projection of `core::resource_usage::ResourceUsageSnapshot`.
/// Identical numeric fields plus the nested project → task → session
/// tree the popover renders. The `app` row is always populated; the
/// `projects` vec is empty when no PTY children are tracked.
class ResourceUsageSnapshotDto {
  final double totalCpuPercent;
  final BigInt totalMemoryBytes;
  final double ramSharePercent;
  final BigInt sessionCount;
  final String appLabel;
  final double appCpuPercent;
  final BigInt appMemoryBytes;
  final List<ResourceUsageProjectDto> projects;

  const ResourceUsageSnapshotDto({
    required this.totalCpuPercent,
    required this.totalMemoryBytes,
    required this.ramSharePercent,
    required this.sessionCount,
    required this.appLabel,
    required this.appCpuPercent,
    required this.appMemoryBytes,
    required this.projects,
  });

  @override
  int get hashCode =>
      totalCpuPercent.hashCode ^
      totalMemoryBytes.hashCode ^
      ramSharePercent.hashCode ^
      sessionCount.hashCode ^
      appLabel.hashCode ^
      appCpuPercent.hashCode ^
      appMemoryBytes.hashCode ^
      projects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceUsageSnapshotDto &&
          runtimeType == other.runtimeType &&
          totalCpuPercent == other.totalCpuPercent &&
          totalMemoryBytes == other.totalMemoryBytes &&
          ramSharePercent == other.ramSharePercent &&
          sessionCount == other.sessionCount &&
          appLabel == other.appLabel &&
          appCpuPercent == other.appCpuPercent &&
          appMemoryBytes == other.appMemoryBytes &&
          projects == other.projects;
}

class ResourceUsageTaskDto {
  final String key;
  final String label;
  final double cpuPercent;
  final BigInt memoryBytes;
  final List<ResourceUsageSessionDto> sessions;

  const ResourceUsageTaskDto({
    required this.key,
    required this.label,
    required this.cpuPercent,
    required this.memoryBytes,
    required this.sessions,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      cpuPercent.hashCode ^
      memoryBytes.hashCode ^
      sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceUsageTaskDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          cpuPercent == other.cpuPercent &&
          memoryBytes == other.memoryBytes &&
          sessions == other.sessions;
}
