// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lookup`, `registry`, `snapshot_to_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineKey`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `hash`

/// Allocate a terminal engine for `(section_id, tab_id)`. Idempotent:
/// reopening with new dimensions resizes the existing engine rather
/// than dropping its grid state.
Future<void> engineOpen({
  required String sectionId,
  required String tabId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalEngineEngineOpen(
  sectionId: sectionId,
  tabId: tabId,
  cols: cols,
  rows: rows,
);

Future<void> engineWritePty({
  required String sectionId,
  required String tabId,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTerminalEngineEngineWritePty(
  sectionId: sectionId,
  tabId: tabId,
  bytes: bytes,
);

Future<void> engineResize({
  required String sectionId,
  required String tabId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalEngineEngineResize(
  sectionId: sectionId,
  tabId: tabId,
  cols: cols,
  rows: rows,
);

/// Cheap per-frame poll for the renderer. Returns just the engine's
/// revision counter (`u64` round-trip) so the Flutter Ticker can
/// skip the full `engine_snapshot` (`Vec<CellDto>` serialise across
/// FRB) when the cell grid is unchanged. Without this fast path an
/// idle terminal burns ~2 cores at 60 Hz on a typical 80×24 grid.
Future<BigInt> engineRevision({
  required String sectionId,
  required String tabId,
}) => RustLib.instance.api.crateApiTerminalEngineEngineRevision(
  sectionId: sectionId,
  tabId: tabId,
);

Future<SnapshotDto> engineSnapshot({
  required String sectionId,
  required String tabId,
  required int scrollbackOffset,
  required int maxRows,
}) => RustLib.instance.api.crateApiTerminalEngineEngineSnapshot(
  sectionId: sectionId,
  tabId: tabId,
  scrollbackOffset: scrollbackOffset,
  maxRows: maxRows,
);

Future<Uint8List> engineEncodeInput({
  required String sectionId,
  required String tabId,
  required InputEventDto event,
}) => RustLib.instance.api.crateApiTerminalEngineEngineEncodeInput(
  sectionId: sectionId,
  tabId: tabId,
  event: event,
);

Future<void> engineClose({required String sectionId, required String tabId}) =>
    RustLib.instance.api.crateApiTerminalEngineEngineClose(
      sectionId: sectionId,
      tabId: tabId,
    );

class CellDto {
  final int ch;
  final int fg;
  final int bg;
  final int flags;

  const CellDto({
    required this.ch,
    required this.fg,
    required this.bg,
    required this.flags,
  });

  @override
  int get hashCode => ch.hashCode ^ fg.hashCode ^ bg.hashCode ^ flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CellDto &&
          runtimeType == other.runtimeType &&
          ch == other.ch &&
          fg == other.fg &&
          bg == other.bg &&
          flags == other.flags;
}

/// Wire-side mirror of [`core_engine::InputEvent`]. Tagged-union via
/// `kind` + `code` to keep the FRB bridge tight; expanding the
/// variant set later just adds new `kind` values.
///
/// `kind`:
/// * 0 = Char (uses `code` as the codepoint)
/// * 1 = Enter
/// * 2 = Backspace
/// * 3 = Tab
/// * 4 = Escape
/// * 5 = ArrowUp
/// * 6 = ArrowDown
/// * 7 = ArrowLeft
/// * 8 = ArrowRight
/// * 9 = Resize (uses `code` low 16 bits = cols, high 16 bits = rows)
class InputEventDto {
  final int kind;
  final int code;

  const InputEventDto({required this.kind, required this.code});

  @override
  int get hashCode => kind.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          code == other.code;
}

/// FRB-flat snapshot DTO. Mirrors [`core_engine::Snapshot`] but with
/// concrete field types FRB can encode (no `bitflags`, no `Option<T>`
/// unless trivial, no `Box<dyn>`).
class SnapshotDto {
  final int cols;
  final int rows;
  final int cursorCol;
  final int cursorRow;
  final bool cursorVisible;

  /// 0 = block, 1 = bar, 2 = underline. Kept as `u8` so future
  /// shapes don't bump the wire tag set.
  final int cursorStyle;

  /// `cells.len() == cols * rows`, row-major. Each entry is a
  /// 16-byte `CellDto`.
  final List<CellDto> cells;
  final BigInt revision;

  const SnapshotDto({
    required this.cols,
    required this.rows,
    required this.cursorCol,
    required this.cursorRow,
    required this.cursorVisible,
    required this.cursorStyle,
    required this.cells,
    required this.revision,
  });

  @override
  int get hashCode =>
      cols.hashCode ^
      rows.hashCode ^
      cursorCol.hashCode ^
      cursorRow.hashCode ^
      cursorVisible.hashCode ^
      cursorStyle.hashCode ^
      cells.hashCode ^
      revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotDto &&
          runtimeType == other.runtimeType &&
          cols == other.cols &&
          rows == other.rows &&
          cursorCol == other.cursorCol &&
          cursorRow == other.cursorRow &&
          cursorVisible == other.cursorVisible &&
          cursorStyle == other.cursorStyle &&
          cells == other.cells &&
          revision == other.revision;
}
