// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/build_info.dart';
import 'api/embedded_daemon.dart';
import 'api/iroh_client.dart';
import 'api/local_session.dart';
import 'api/pair.dart';
import 'api/resources.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_IrohSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSessionPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocalSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSessionPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  IrohSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  );

  @protected
  LocalSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    dynamic raw,
  );

  @protected
  IrohSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  );

  @protected
  LocalSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    dynamic raw,
  );

  @protected
  IrohSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  );

  @protected
  LocalSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    dynamic raw,
  );

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<WorkerReply> dco_decode_StreamSink_worker_reply_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentProvider dco_decode_agent_provider(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AgentProvider dco_decode_box_autoadd_agent_provider(dynamic raw);

  @protected
  PairingInfo dco_decode_box_autoadd_pairing_info(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BuildInfo dco_decode_build_info(dynamic raw);

  @protected
  ChangedFileDto dco_decode_changed_file_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChangedFileDto> dco_decode_list_changed_file_dto(dynamic raw);

  @protected
  List<OpenInAppDto> dco_decode_list_open_in_app_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectSummary> dco_decode_list_project_summary(dynamic raw);

  @protected
  List<TabSummary> dco_decode_list_tab_summary(dynamic raw);

  @protected
  List<TaskSummary> dco_decode_list_task_summary(dynamic raw);

  @protected
  OpenInAppDto dco_decode_open_in_app_dto(dynamic raw);

  @protected
  OpenInState dco_decode_open_in_state(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AgentProvider? dco_decode_opt_box_autoadd_agent_provider(dynamic raw);

  @protected
  PairingInfo? dco_decode_opt_box_autoadd_pairing_info(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<ChangedFileDto>? dco_decode_opt_list_changed_file_dto(dynamic raw);

  @protected
  PairingInfo dco_decode_pairing_info(dynamic raw);

  @protected
  ProjectKind dco_decode_project_kind(dynamic raw);

  @protected
  ProjectSummary dco_decode_project_summary(dynamic raw);

  @protected
  ResourceSample dco_decode_resource_sample(dynamic raw);

  @protected
  TabSummary dco_decode_tab_summary(dynamic raw);

  @protected
  TaskSummary dco_decode_task_summary(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WorkerReply dco_decode_worker_reply(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  IrohSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  );

  @protected
  LocalSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    SseDeserializer deserializer,
  );

  @protected
  IrohSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  );

  @protected
  LocalSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    SseDeserializer deserializer,
  );

  @protected
  IrohSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  );

  @protected
  LocalSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WorkerReply> sse_decode_StreamSink_worker_reply_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentProvider sse_decode_agent_provider(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AgentProvider sse_decode_box_autoadd_agent_provider(
    SseDeserializer deserializer,
  );

  @protected
  PairingInfo sse_decode_box_autoadd_pairing_info(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BuildInfo sse_decode_build_info(SseDeserializer deserializer);

  @protected
  ChangedFileDto sse_decode_changed_file_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChangedFileDto> sse_decode_list_changed_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<OpenInAppDto> sse_decode_list_open_in_app_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectSummary> sse_decode_list_project_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<TabSummary> sse_decode_list_tab_summary(SseDeserializer deserializer);

  @protected
  List<TaskSummary> sse_decode_list_task_summary(SseDeserializer deserializer);

  @protected
  OpenInAppDto sse_decode_open_in_app_dto(SseDeserializer deserializer);

  @protected
  OpenInState sse_decode_open_in_state(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AgentProvider? sse_decode_opt_box_autoadd_agent_provider(
    SseDeserializer deserializer,
  );

  @protected
  PairingInfo? sse_decode_opt_box_autoadd_pairing_info(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<ChangedFileDto>? sse_decode_opt_list_changed_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  PairingInfo sse_decode_pairing_info(SseDeserializer deserializer);

  @protected
  ProjectKind sse_decode_project_kind(SseDeserializer deserializer);

  @protected
  ProjectSummary sse_decode_project_summary(SseDeserializer deserializer);

  @protected
  ResourceSample sse_decode_resource_sample(SseDeserializer deserializer);

  @protected
  TabSummary sse_decode_tab_summary(SseDeserializer deserializer);

  @protected
  TaskSummary sse_decode_task_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WorkerReply sse_decode_worker_reply(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    LocalSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    LocalSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    LocalSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_worker_reply_Sse(
    RustStreamSink<WorkerReply> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_provider(AgentProvider self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_provider(
    AgentProvider self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pairing_info(
    PairingInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_build_info(BuildInfo self, SseSerializer serializer);

  @protected
  void sse_encode_changed_file_dto(
    ChangedFileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_changed_file_dto(
    List<ChangedFileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_open_in_app_dto(
    List<OpenInAppDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_summary(
    List<ProjectSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tab_summary(
    List<TabSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_summary(
    List<TaskSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_in_app_dto(OpenInAppDto self, SseSerializer serializer);

  @protected
  void sse_encode_open_in_state(OpenInState self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_agent_provider(
    AgentProvider? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pairing_info(
    PairingInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_changed_file_dto(
    List<ChangedFileDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_info(PairingInfo self, SseSerializer serializer);

  @protected
  void sse_encode_project_kind(ProjectKind self, SseSerializer serializer);

  @protected
  void sse_encode_project_summary(
    ProjectSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_sample(
    ResourceSample self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tab_summary(TabSummary self, SseSerializer serializer);

  @protected
  void sse_encode_task_summary(TaskSummary self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_worker_reply(WorkerReply self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_another_one_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_another_one_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_another_one_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_another_one_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
