// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/build_info.dart';
import 'api/embedded_daemon.dart';
import 'api/iroh_client.dart';
import 'api/local_session.dart';
import 'api/pair.dart';
import 'api/resources.dart';
import 'api/terminal_engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_IrohSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocalSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  IrohSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  );

  @protected
  LocalSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    dynamic raw,
  );

  @protected
  IrohSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  );

  @protected
  LocalSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    dynamic raw,
  );

  @protected
  IrohSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  );

  @protected
  LocalSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    dynamic raw,
  );

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<WorkerReply> dco_decode_StreamSink_worker_reply_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<WorkerReplyMessage>
  dco_decode_StreamSink_worker_reply_message_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveGitStateDto dco_decode_active_git_state_dto(dynamic raw);

  @protected
  ActiveGitStateWire dco_decode_active_git_state_wire(dynamic raw);

  @protected
  AgentProvider dco_decode_agent_provider(dynamic raw);

  @protected
  AgentSettingsRow dco_decode_agent_settings_row(dynamic raw);

  @protected
  AgentSettingsView dco_decode_agent_settings_view(dynamic raw);

  @protected
  AgentSummaryDto dco_decode_agent_summary_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActiveGitStateDto dco_decode_box_autoadd_active_git_state_dto(dynamic raw);

  @protected
  ActiveGitStateWire dco_decode_box_autoadd_active_git_state_wire(dynamic raw);

  @protected
  AgentProvider dco_decode_box_autoadd_agent_provider(dynamic raw);

  @protected
  BranchCompareView dco_decode_box_autoadd_branch_compare_view(dynamic raw);

  @protected
  BranchCompareWire dco_decode_box_autoadd_branch_compare_wire(dynamic raw);

  @protected
  InputEventDto dco_decode_box_autoadd_input_event_dto(dynamic raw);

  @protected
  PairingInfo dco_decode_box_autoadd_pairing_info(dynamic raw);

  @protected
  ProjectActionDto dco_decode_box_autoadd_project_action_dto(dynamic raw);

  @protected
  PullRequestStatusDto dco_decode_box_autoadd_pull_request_status_dto(
    dynamic raw,
  );

  @protected
  RecentCommitsView dco_decode_box_autoadd_recent_commits_view(dynamic raw);

  @protected
  RecentCommitsWire dco_decode_box_autoadd_recent_commits_wire(dynamic raw);

  @protected
  ResolvedProjectBranchSettingsDto
  dco_decode_box_autoadd_resolved_project_branch_settings_dto(dynamic raw);

  @protected
  ResourceUsageSnapshotDto dco_decode_box_autoadd_resource_usage_snapshot_dto(
    dynamic raw,
  );

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BranchCompareFileDto dco_decode_branch_compare_file_dto(dynamic raw);

  @protected
  BranchCompareFileWire dco_decode_branch_compare_file_wire(dynamic raw);

  @protected
  BranchCompareView dco_decode_branch_compare_view(dynamic raw);

  @protected
  BranchCompareWire dco_decode_branch_compare_wire(dynamic raw);

  @protected
  BuildInfo dco_decode_build_info(dynamic raw);

  @protected
  CellDto dco_decode_cell_dto(dynamic raw);

  @protected
  ChangedFileDto dco_decode_changed_file_dto(dynamic raw);

  @protected
  ChangedFileWire dco_decode_changed_file_wire(dynamic raw);

  @protected
  CheckBucket dco_decode_check_bucket(dynamic raw);

  @protected
  CheckDto dco_decode_check_dto(dynamic raw);

  @protected
  CommitDto dco_decode_commit_dto(dynamic raw);

  @protected
  CommitWire dco_decode_commit_wire(dynamic raw);

  @protected
  EnabledAgentsView dco_decode_enabled_agents_view(dynamic raw);

  @protected
  ErrKind dco_decode_err_kind(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GitActionScriptsView dco_decode_git_action_scripts_view(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InputEventDto dco_decode_input_event_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentSettingsRow> dco_decode_list_agent_settings_row(dynamic raw);

  @protected
  List<AgentSummaryDto> dco_decode_list_agent_summary_dto(dynamic raw);

  @protected
  List<BranchCompareFileDto> dco_decode_list_branch_compare_file_dto(
    dynamic raw,
  );

  @protected
  List<BranchCompareFileWire> dco_decode_list_branch_compare_file_wire(
    dynamic raw,
  );

  @protected
  List<CellDto> dco_decode_list_cell_dto(dynamic raw);

  @protected
  List<ChangedFileDto> dco_decode_list_changed_file_dto(dynamic raw);

  @protected
  List<ChangedFileWire> dco_decode_list_changed_file_wire(dynamic raw);

  @protected
  List<CheckDto> dco_decode_list_check_dto(dynamic raw);

  @protected
  List<CommitDto> dco_decode_list_commit_dto(dynamic raw);

  @protected
  List<CommitWire> dco_decode_list_commit_wire(dynamic raw);

  @protected
  List<McpCatalogEntryDto> dco_decode_list_mcp_catalog_entry_dto(dynamic raw);

  @protected
  List<McpServerDto> dco_decode_list_mcp_server_dto(dynamic raw);

  @protected
  List<OpenInAppDto> dco_decode_list_open_in_app_dto(dynamic raw);

  @protected
  List<OpenInAppSettingsRow> dco_decode_list_open_in_app_settings_row(
    dynamic raw,
  );

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectActionDto> dco_decode_list_project_action_dto(dynamic raw);

  @protected
  List<ProjectPagePullRequestDto> dco_decode_list_project_page_pull_request_dto(
    dynamic raw,
  );

  @protected
  List<ProjectSummary> dco_decode_list_project_summary(dynamic raw);

  @protected
  List<ResourceUsageProjectDto> dco_decode_list_resource_usage_project_dto(
    dynamic raw,
  );

  @protected
  List<ResourceUsageSessionDto> dco_decode_list_resource_usage_session_dto(
    dynamic raw,
  );

  @protected
  List<ResourceUsageTaskDto> dco_decode_list_resource_usage_task_dto(
    dynamic raw,
  );

  @protected
  List<ShortcutSettingsRow> dco_decode_list_shortcut_settings_row(dynamic raw);

  @protected
  List<TabSummary> dco_decode_list_tab_summary(dynamic raw);

  @protected
  List<TaskSummary> dco_decode_list_task_summary(dynamic raw);

  @protected
  McpCatalogEntryDto dco_decode_mcp_catalog_entry_dto(dynamic raw);

  @protected
  McpServerDto dco_decode_mcp_server_dto(dynamic raw);

  @protected
  McpSettingsView dco_decode_mcp_settings_view(dynamic raw);

  @protected
  McpSourceDto dco_decode_mcp_source_dto(dynamic raw);

  @protected
  McpTransportKindDto dco_decode_mcp_transport_kind_dto(dynamic raw);

  @protected
  OpenInAppDto dco_decode_open_in_app_dto(dynamic raw);

  @protected
  OpenInAppSettingsRow dco_decode_open_in_app_settings_row(dynamic raw);

  @protected
  OpenInSettingsView dco_decode_open_in_settings_view(dynamic raw);

  @protected
  OpenInState dco_decode_open_in_state(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ActiveGitStateDto? dco_decode_opt_box_autoadd_active_git_state_dto(
    dynamic raw,
  );

  @protected
  ActiveGitStateWire? dco_decode_opt_box_autoadd_active_git_state_wire(
    dynamic raw,
  );

  @protected
  AgentProvider? dco_decode_opt_box_autoadd_agent_provider(dynamic raw);

  @protected
  BranchCompareView? dco_decode_opt_box_autoadd_branch_compare_view(
    dynamic raw,
  );

  @protected
  BranchCompareWire? dco_decode_opt_box_autoadd_branch_compare_wire(
    dynamic raw,
  );

  @protected
  PairingInfo? dco_decode_opt_box_autoadd_pairing_info(dynamic raw);

  @protected
  PullRequestStatusDto? dco_decode_opt_box_autoadd_pull_request_status_dto(
    dynamic raw,
  );

  @protected
  RecentCommitsView? dco_decode_opt_box_autoadd_recent_commits_view(
    dynamic raw,
  );

  @protected
  RecentCommitsWire? dco_decode_opt_box_autoadd_recent_commits_wire(
    dynamic raw,
  );

  @protected
  ResolvedProjectBranchSettingsDto?
  dco_decode_opt_box_autoadd_resolved_project_branch_settings_dto(dynamic raw);

  @protected
  ResourceUsageSnapshotDto?
  dco_decode_opt_box_autoadd_resource_usage_snapshot_dto(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<BranchCompareFileDto>? dco_decode_opt_list_branch_compare_file_dto(
    dynamic raw,
  );

  @protected
  List<BranchCompareFileWire>? dco_decode_opt_list_branch_compare_file_wire(
    dynamic raw,
  );

  @protected
  List<ChangedFileDto>? dco_decode_opt_list_changed_file_dto(dynamic raw);

  @protected
  List<ChangedFileWire>? dco_decode_opt_list_changed_file_wire(dynamic raw);

  @protected
  List<CheckDto>? dco_decode_opt_list_check_dto(dynamic raw);

  @protected
  List<ProjectPagePullRequestDto>?
  dco_decode_opt_list_project_page_pull_request_dto(dynamic raw);

  @protected
  PairingInfo dco_decode_pairing_info(dynamic raw);

  @protected
  ProjectActionAccessDto dco_decode_project_action_access_dto(dynamic raw);

  @protected
  ProjectActionDto dco_decode_project_action_dto(dynamic raw);

  @protected
  ProjectActionIconDto dco_decode_project_action_icon_dto(dynamic raw);

  @protected
  ProjectActionKindDto dco_decode_project_action_kind_dto(dynamic raw);

  @protected
  ProjectActionScopeDto dco_decode_project_action_scope_dto(dynamic raw);

  @protected
  ProjectKind dco_decode_project_kind(dynamic raw);

  @protected
  ProjectPagePullRequestDto dco_decode_project_page_pull_request_dto(
    dynamic raw,
  );

  @protected
  ProjectSummary dco_decode_project_summary(dynamic raw);

  @protected
  PullRequestStateDto dco_decode_pull_request_state_dto(dynamic raw);

  @protected
  PullRequestStatusDto dco_decode_pull_request_status_dto(dynamic raw);

  @protected
  RecentCommitsView dco_decode_recent_commits_view(dynamic raw);

  @protected
  RecentCommitsWire dco_decode_recent_commits_wire(dynamic raw);

  @protected
  ResolvedProjectBranchSettingsDto
  dco_decode_resolved_project_branch_settings_dto(dynamic raw);

  @protected
  ResourceSample dco_decode_resource_sample(dynamic raw);

  @protected
  ResourceUsageProjectDto dco_decode_resource_usage_project_dto(dynamic raw);

  @protected
  ResourceUsageSessionDto dco_decode_resource_usage_session_dto(dynamic raw);

  @protected
  ResourceUsageSnapshotDto dco_decode_resource_usage_snapshot_dto(dynamic raw);

  @protected
  ResourceUsageTaskDto dco_decode_resource_usage_task_dto(dynamic raw);

  @protected
  ShortcutSettingsRow dco_decode_shortcut_settings_row(dynamic raw);

  @protected
  ShortcutSettingsView dco_decode_shortcut_settings_view(dynamic raw);

  @protected
  SnapshotDto dco_decode_snapshot_dto(dynamic raw);

  @protected
  TabSummary dco_decode_tab_summary(dynamic raw);

  @protected
  TaskSummary dco_decode_task_summary(dynamic raw);

  @protected
  ToolbarActionOutcomeDto dco_decode_toolbar_action_outcome_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WorkerReply dco_decode_worker_reply(dynamic raw);

  @protected
  WorkerReplyMessage dco_decode_worker_reply_message(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  IrohSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  );

  @protected
  LocalSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    SseDeserializer deserializer,
  );

  @protected
  IrohSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  );

  @protected
  LocalSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    SseDeserializer deserializer,
  );

  @protected
  IrohSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  );

  @protected
  LocalSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WorkerReply> sse_decode_StreamSink_worker_reply_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WorkerReplyMessage>
  sse_decode_StreamSink_worker_reply_message_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveGitStateDto sse_decode_active_git_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  ActiveGitStateWire sse_decode_active_git_state_wire(
    SseDeserializer deserializer,
  );

  @protected
  AgentProvider sse_decode_agent_provider(SseDeserializer deserializer);

  @protected
  AgentSettingsRow sse_decode_agent_settings_row(SseDeserializer deserializer);

  @protected
  AgentSettingsView sse_decode_agent_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  AgentSummaryDto sse_decode_agent_summary_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActiveGitStateDto sse_decode_box_autoadd_active_git_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  ActiveGitStateWire sse_decode_box_autoadd_active_git_state_wire(
    SseDeserializer deserializer,
  );

  @protected
  AgentProvider sse_decode_box_autoadd_agent_provider(
    SseDeserializer deserializer,
  );

  @protected
  BranchCompareView sse_decode_box_autoadd_branch_compare_view(
    SseDeserializer deserializer,
  );

  @protected
  BranchCompareWire sse_decode_box_autoadd_branch_compare_wire(
    SseDeserializer deserializer,
  );

  @protected
  InputEventDto sse_decode_box_autoadd_input_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  PairingInfo sse_decode_box_autoadd_pairing_info(SseDeserializer deserializer);

  @protected
  ProjectActionDto sse_decode_box_autoadd_project_action_dto(
    SseDeserializer deserializer,
  );

  @protected
  PullRequestStatusDto sse_decode_box_autoadd_pull_request_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecentCommitsView sse_decode_box_autoadd_recent_commits_view(
    SseDeserializer deserializer,
  );

  @protected
  RecentCommitsWire sse_decode_box_autoadd_recent_commits_wire(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedProjectBranchSettingsDto
  sse_decode_box_autoadd_resolved_project_branch_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResourceUsageSnapshotDto sse_decode_box_autoadd_resource_usage_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BranchCompareFileDto sse_decode_branch_compare_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  BranchCompareFileWire sse_decode_branch_compare_file_wire(
    SseDeserializer deserializer,
  );

  @protected
  BranchCompareView sse_decode_branch_compare_view(
    SseDeserializer deserializer,
  );

  @protected
  BranchCompareWire sse_decode_branch_compare_wire(
    SseDeserializer deserializer,
  );

  @protected
  BuildInfo sse_decode_build_info(SseDeserializer deserializer);

  @protected
  CellDto sse_decode_cell_dto(SseDeserializer deserializer);

  @protected
  ChangedFileDto sse_decode_changed_file_dto(SseDeserializer deserializer);

  @protected
  ChangedFileWire sse_decode_changed_file_wire(SseDeserializer deserializer);

  @protected
  CheckBucket sse_decode_check_bucket(SseDeserializer deserializer);

  @protected
  CheckDto sse_decode_check_dto(SseDeserializer deserializer);

  @protected
  CommitDto sse_decode_commit_dto(SseDeserializer deserializer);

  @protected
  CommitWire sse_decode_commit_wire(SseDeserializer deserializer);

  @protected
  EnabledAgentsView sse_decode_enabled_agents_view(
    SseDeserializer deserializer,
  );

  @protected
  ErrKind sse_decode_err_kind(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GitActionScriptsView sse_decode_git_action_scripts_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InputEventDto sse_decode_input_event_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentSettingsRow> sse_decode_list_agent_settings_row(
    SseDeserializer deserializer,
  );

  @protected
  List<AgentSummaryDto> sse_decode_list_agent_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BranchCompareFileDto> sse_decode_list_branch_compare_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BranchCompareFileWire> sse_decode_list_branch_compare_file_wire(
    SseDeserializer deserializer,
  );

  @protected
  List<CellDto> sse_decode_list_cell_dto(SseDeserializer deserializer);

  @protected
  List<ChangedFileDto> sse_decode_list_changed_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ChangedFileWire> sse_decode_list_changed_file_wire(
    SseDeserializer deserializer,
  );

  @protected
  List<CheckDto> sse_decode_list_check_dto(SseDeserializer deserializer);

  @protected
  List<CommitDto> sse_decode_list_commit_dto(SseDeserializer deserializer);

  @protected
  List<CommitWire> sse_decode_list_commit_wire(SseDeserializer deserializer);

  @protected
  List<McpCatalogEntryDto> sse_decode_list_mcp_catalog_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<McpServerDto> sse_decode_list_mcp_server_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<OpenInAppDto> sse_decode_list_open_in_app_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<OpenInAppSettingsRow> sse_decode_list_open_in_app_settings_row(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectActionDto> sse_decode_list_project_action_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ProjectPagePullRequestDto> sse_decode_list_project_page_pull_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ProjectSummary> sse_decode_list_project_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<ResourceUsageProjectDto> sse_decode_list_resource_usage_project_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ResourceUsageSessionDto> sse_decode_list_resource_usage_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ResourceUsageTaskDto> sse_decode_list_resource_usage_task_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ShortcutSettingsRow> sse_decode_list_shortcut_settings_row(
    SseDeserializer deserializer,
  );

  @protected
  List<TabSummary> sse_decode_list_tab_summary(SseDeserializer deserializer);

  @protected
  List<TaskSummary> sse_decode_list_task_summary(SseDeserializer deserializer);

  @protected
  McpCatalogEntryDto sse_decode_mcp_catalog_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  McpServerDto sse_decode_mcp_server_dto(SseDeserializer deserializer);

  @protected
  McpSettingsView sse_decode_mcp_settings_view(SseDeserializer deserializer);

  @protected
  McpSourceDto sse_decode_mcp_source_dto(SseDeserializer deserializer);

  @protected
  McpTransportKindDto sse_decode_mcp_transport_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  OpenInAppDto sse_decode_open_in_app_dto(SseDeserializer deserializer);

  @protected
  OpenInAppSettingsRow sse_decode_open_in_app_settings_row(
    SseDeserializer deserializer,
  );

  @protected
  OpenInSettingsView sse_decode_open_in_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  OpenInState sse_decode_open_in_state(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ActiveGitStateDto? sse_decode_opt_box_autoadd_active_git_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  ActiveGitStateWire? sse_decode_opt_box_autoadd_active_git_state_wire(
    SseDeserializer deserializer,
  );

  @protected
  AgentProvider? sse_decode_opt_box_autoadd_agent_provider(
    SseDeserializer deserializer,
  );

  @protected
  BranchCompareView? sse_decode_opt_box_autoadd_branch_compare_view(
    SseDeserializer deserializer,
  );

  @protected
  BranchCompareWire? sse_decode_opt_box_autoadd_branch_compare_wire(
    SseDeserializer deserializer,
  );

  @protected
  PairingInfo? sse_decode_opt_box_autoadd_pairing_info(
    SseDeserializer deserializer,
  );

  @protected
  PullRequestStatusDto? sse_decode_opt_box_autoadd_pull_request_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecentCommitsView? sse_decode_opt_box_autoadd_recent_commits_view(
    SseDeserializer deserializer,
  );

  @protected
  RecentCommitsWire? sse_decode_opt_box_autoadd_recent_commits_wire(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedProjectBranchSettingsDto?
  sse_decode_opt_box_autoadd_resolved_project_branch_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResourceUsageSnapshotDto?
  sse_decode_opt_box_autoadd_resource_usage_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<BranchCompareFileDto>? sse_decode_opt_list_branch_compare_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BranchCompareFileWire>? sse_decode_opt_list_branch_compare_file_wire(
    SseDeserializer deserializer,
  );

  @protected
  List<ChangedFileDto>? sse_decode_opt_list_changed_file_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ChangedFileWire>? sse_decode_opt_list_changed_file_wire(
    SseDeserializer deserializer,
  );

  @protected
  List<CheckDto>? sse_decode_opt_list_check_dto(SseDeserializer deserializer);

  @protected
  List<ProjectPagePullRequestDto>?
  sse_decode_opt_list_project_page_pull_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  PairingInfo sse_decode_pairing_info(SseDeserializer deserializer);

  @protected
  ProjectActionAccessDto sse_decode_project_action_access_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectActionDto sse_decode_project_action_dto(SseDeserializer deserializer);

  @protected
  ProjectActionIconDto sse_decode_project_action_icon_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectActionKindDto sse_decode_project_action_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectActionScopeDto sse_decode_project_action_scope_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectKind sse_decode_project_kind(SseDeserializer deserializer);

  @protected
  ProjectPagePullRequestDto sse_decode_project_page_pull_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectSummary sse_decode_project_summary(SseDeserializer deserializer);

  @protected
  PullRequestStateDto sse_decode_pull_request_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  PullRequestStatusDto sse_decode_pull_request_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecentCommitsView sse_decode_recent_commits_view(
    SseDeserializer deserializer,
  );

  @protected
  RecentCommitsWire sse_decode_recent_commits_wire(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedProjectBranchSettingsDto
  sse_decode_resolved_project_branch_settings_dto(SseDeserializer deserializer);

  @protected
  ResourceSample sse_decode_resource_sample(SseDeserializer deserializer);

  @protected
  ResourceUsageProjectDto sse_decode_resource_usage_project_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResourceUsageSessionDto sse_decode_resource_usage_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResourceUsageSnapshotDto sse_decode_resource_usage_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResourceUsageTaskDto sse_decode_resource_usage_task_dto(
    SseDeserializer deserializer,
  );

  @protected
  ShortcutSettingsRow sse_decode_shortcut_settings_row(
    SseDeserializer deserializer,
  );

  @protected
  ShortcutSettingsView sse_decode_shortcut_settings_view(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotDto sse_decode_snapshot_dto(SseDeserializer deserializer);

  @protected
  TabSummary sse_decode_tab_summary(SseDeserializer deserializer);

  @protected
  TaskSummary sse_decode_task_summary(SseDeserializer deserializer);

  @protected
  ToolbarActionOutcomeDto sse_decode_toolbar_action_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WorkerReply sse_decode_worker_reply(SseDeserializer deserializer);

  @protected
  WorkerReplyMessage sse_decode_worker_reply_message(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    LocalSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    LocalSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    LocalSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_worker_reply_Sse(
    RustStreamSink<WorkerReply> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_worker_reply_message_Sse(
    RustStreamSink<WorkerReplyMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_git_state_dto(
    ActiveGitStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_active_git_state_wire(
    ActiveGitStateWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_provider(AgentProvider self, SseSerializer serializer);

  @protected
  void sse_encode_agent_settings_row(
    AgentSettingsRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_settings_view(
    AgentSettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_summary_dto(
    AgentSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_active_git_state_dto(
    ActiveGitStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_active_git_state_wire(
    ActiveGitStateWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_agent_provider(
    AgentProvider self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_branch_compare_view(
    BranchCompareView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_branch_compare_wire(
    BranchCompareWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_input_event_dto(
    InputEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pairing_info(
    PairingInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_project_action_dto(
    ProjectActionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pull_request_status_dto(
    PullRequestStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_recent_commits_view(
    RecentCommitsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_recent_commits_wire(
    RecentCommitsWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resolved_project_branch_settings_dto(
    ResolvedProjectBranchSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resource_usage_snapshot_dto(
    ResourceUsageSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_branch_compare_file_dto(
    BranchCompareFileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_branch_compare_file_wire(
    BranchCompareFileWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_branch_compare_view(
    BranchCompareView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_branch_compare_wire(
    BranchCompareWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_build_info(BuildInfo self, SseSerializer serializer);

  @protected
  void sse_encode_cell_dto(CellDto self, SseSerializer serializer);

  @protected
  void sse_encode_changed_file_dto(
    ChangedFileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_changed_file_wire(
    ChangedFileWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_check_bucket(CheckBucket self, SseSerializer serializer);

  @protected
  void sse_encode_check_dto(CheckDto self, SseSerializer serializer);

  @protected
  void sse_encode_commit_dto(CommitDto self, SseSerializer serializer);

  @protected
  void sse_encode_commit_wire(CommitWire self, SseSerializer serializer);

  @protected
  void sse_encode_enabled_agents_view(
    EnabledAgentsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_err_kind(ErrKind self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_git_action_scripts_view(
    GitActionScriptsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_input_event_dto(InputEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_settings_row(
    List<AgentSettingsRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_agent_summary_dto(
    List<AgentSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_branch_compare_file_dto(
    List<BranchCompareFileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_branch_compare_file_wire(
    List<BranchCompareFileWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cell_dto(List<CellDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_changed_file_dto(
    List<ChangedFileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_changed_file_wire(
    List<ChangedFileWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_check_dto(List<CheckDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_commit_dto(
    List<CommitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_commit_wire(
    List<CommitWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mcp_catalog_entry_dto(
    List<McpCatalogEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mcp_server_dto(
    List<McpServerDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_open_in_app_dto(
    List<OpenInAppDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_open_in_app_settings_row(
    List<OpenInAppSettingsRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_action_dto(
    List<ProjectActionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_page_pull_request_dto(
    List<ProjectPagePullRequestDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_summary(
    List<ProjectSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resource_usage_project_dto(
    List<ResourceUsageProjectDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resource_usage_session_dto(
    List<ResourceUsageSessionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resource_usage_task_dto(
    List<ResourceUsageTaskDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shortcut_settings_row(
    List<ShortcutSettingsRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tab_summary(
    List<TabSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_summary(
    List<TaskSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_catalog_entry_dto(
    McpCatalogEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_server_dto(McpServerDto self, SseSerializer serializer);

  @protected
  void sse_encode_mcp_settings_view(
    McpSettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_source_dto(McpSourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_mcp_transport_kind_dto(
    McpTransportKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_in_app_dto(OpenInAppDto self, SseSerializer serializer);

  @protected
  void sse_encode_open_in_app_settings_row(
    OpenInAppSettingsRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_in_settings_view(
    OpenInSettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_in_state(OpenInState self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_active_git_state_dto(
    ActiveGitStateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_active_git_state_wire(
    ActiveGitStateWire? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_agent_provider(
    AgentProvider? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_branch_compare_view(
    BranchCompareView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_branch_compare_wire(
    BranchCompareWire? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pairing_info(
    PairingInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pull_request_status_dto(
    PullRequestStatusDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_recent_commits_view(
    RecentCommitsView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_recent_commits_wire(
    RecentCommitsWire? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_resolved_project_branch_settings_dto(
    ResolvedProjectBranchSettingsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_resource_usage_snapshot_dto(
    ResourceUsageSnapshotDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_branch_compare_file_dto(
    List<BranchCompareFileDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_branch_compare_file_wire(
    List<BranchCompareFileWire>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_changed_file_dto(
    List<ChangedFileDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_changed_file_wire(
    List<ChangedFileWire>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_check_dto(
    List<CheckDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_project_page_pull_request_dto(
    List<ProjectPagePullRequestDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_info(PairingInfo self, SseSerializer serializer);

  @protected
  void sse_encode_project_action_access_dto(
    ProjectActionAccessDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_action_dto(
    ProjectActionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_action_icon_dto(
    ProjectActionIconDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_action_kind_dto(
    ProjectActionKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_action_scope_dto(
    ProjectActionScopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_kind(ProjectKind self, SseSerializer serializer);

  @protected
  void sse_encode_project_page_pull_request_dto(
    ProjectPagePullRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_summary(
    ProjectSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pull_request_state_dto(
    PullRequestStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pull_request_status_dto(
    PullRequestStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recent_commits_view(
    RecentCommitsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recent_commits_wire(
    RecentCommitsWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolved_project_branch_settings_dto(
    ResolvedProjectBranchSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_sample(
    ResourceSample self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_usage_project_dto(
    ResourceUsageProjectDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_usage_session_dto(
    ResourceUsageSessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_usage_snapshot_dto(
    ResourceUsageSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_usage_task_dto(
    ResourceUsageTaskDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shortcut_settings_row(
    ShortcutSettingsRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shortcut_settings_view(
    ShortcutSettingsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_snapshot_dto(SnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_tab_summary(TabSummary self, SseSerializer serializer);

  @protected
  void sse_encode_task_summary(TaskSummary self, SseSerializer serializer);

  @protected
  void sse_encode_toolbar_action_outcome_dto(
    ToolbarActionOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_worker_reply(WorkerReply self, SseSerializer serializer);

  @protected
  void sse_encode_worker_reply_message(
    WorkerReplyMessage self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalSession(
    int ptr,
  );
}
