//! Shared data types for terminal launch + runtime.
//!
//! These sit in core so both the launcher (pure PTY spawning, also in
//! core) and the runtime renderer (GPUI-coupled, in desktop) can
//! reference them without one side reaching into the other.
//!
//! Nothing here touches GPUI. `TerminalGridSize` does implement
//! `alacritty_terminal::Dimensions` so both the launcher and the
//! renderer can feed the same value to alacritty, but alacritty_terminal
//! itself is portable.

use std::io::Write;

use alacritty_terminal::grid::Dimensions;
use portable_pty::{ChildKiller, MasterPty, PtySize};
use serde::{Deserialize, Serialize};

use crate::section::SectionId;

/// Clamp floor: terminal must be at least 20 cols wide so prompts render.
/// Crate-private — only `from_panel_size` uses it.
const MIN_TERMINAL_COLS: u16 = 20;

/// Clamp floor: at least 4 rows tall. Crate-private.
const MIN_TERMINAL_ROWS: u16 = 4;

/// How wide one cell is, as a fraction of the font size. Tuned to match
/// Lilex NerdFont Mono at the default weight. `pub` because the desktop
/// renderer uses the same ratio when sizing its grid.
pub const TERMINAL_CELL_WIDTH_RATIO: f32 = 0.62;

/// How tall one line is, as a multiple of the font size. `pub` for the
/// same reason.
pub const TERMINAL_LINE_HEIGHT_RATIO: f32 = 1.25;

/// Stable handle for a live terminal: the section it belongs to + the
/// tab id. Used as a map key across launch/runtime/app state.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct TerminalRuntimeKey {
    pub section_id: SectionId,
    pub tab_id: String,
}

/// Grid size in both character units (cols/rows for the VT state
/// machine) and pixel units (for the rendering layer). The launcher
/// sets this at spawn time; the renderer may update it on resize.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TerminalGridSize {
    pub cols: u16,
    pub rows: u16,
    pub pixel_width: u16,
    pub pixel_height: u16,
}

impl Default for TerminalGridSize {
    fn default() -> Self {
        Self {
            cols: 80,
            rows: 24,
            pixel_width: 0,
            pixel_height: 0,
        }
    }
}

impl TerminalGridSize {
    /// Derive a grid size from a pixel-sized panel and the current font
    /// size. Clamped to [`MIN_TERMINAL_COLS`] / [`MIN_TERMINAL_ROWS`]
    /// so a tiny panel doesn't produce a 0x0 PTY.
    pub fn from_panel_size(width_px: f32, height_px: f32, font_size: f32) -> Self {
        let cell_width = (font_size * TERMINAL_CELL_WIDTH_RATIO).max(7.0);
        let cell_height = (font_size * TERMINAL_LINE_HEIGHT_RATIO).max(14.0);
        let cols = (width_px / cell_width)
            .floor()
            .max(MIN_TERMINAL_COLS as f32) as u16;
        let rows = (height_px / cell_height)
            .floor()
            .max(MIN_TERMINAL_ROWS as f32) as u16;
        Self {
            cols,
            rows,
            pixel_width: width_px.max(0.0).min(u16::MAX as f32) as u16,
            pixel_height: height_px.max(0.0).min(u16::MAX as f32) as u16,
        }
    }

    pub fn as_pty_size(self) -> PtySize {
        PtySize {
            rows: self.rows,
            cols: self.cols,
            pixel_width: self.pixel_width,
            pixel_height: self.pixel_height,
        }
    }
}

impl Dimensions for TerminalGridSize {
    fn total_lines(&self) -> usize {
        self.rows as usize
    }

    fn screen_lines(&self) -> usize {
        self.rows as usize
    }

    fn columns(&self) -> usize {
        self.cols as usize
    }
}

/// UI-agnostic terminal input intent that can be encoded into PTY bytes.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum TerminalInputEvent {
    /// Already-encoded keyboard bytes, including escape sequences for
    /// arrows/function keys/modifiers.
    Key { bytes: Vec<u8> },
    /// Committed text from IME or normal text entry.
    Text { text: String },
    /// Paste payload. Bracketed paste is a terminal mode decision held
    /// by the renderer/client, not by the daemon.
    Paste { text: String, bracketed: bool },
    /// Focus in/out report for terminals that requested focus tracking.
    Focus { focused: bool },
    /// Already-encoded terminal mouse protocol bytes.
    Mouse { bytes: Vec<u8> },
    /// Reply bytes generated by the terminal parser/renderer, such as
    /// device-status or color-query replies.
    PtyReply { bytes: Vec<u8> },
}

impl TerminalInputEvent {
    pub fn pty_bytes(&self) -> Vec<u8> {
        match self {
            Self::Key { bytes } | Self::Mouse { bytes } | Self::PtyReply { bytes } => bytes.clone(),
            Self::Text { text } => text.as_bytes().to_vec(),
            Self::Paste { text, bracketed } => {
                if *bracketed {
                    let mut bytes = Vec::with_capacity(text.len() + 12);
                    bytes.extend_from_slice(b"\x1b[200~");
                    bytes.extend_from_slice(text.as_bytes());
                    bytes.extend_from_slice(b"\x1b[201~");
                    bytes
                } else {
                    text.as_bytes().to_vec()
                }
            }
            Self::Focus { focused } => {
                if *focused {
                    b"\x1b[I".to_vec()
                } else {
                    b"\x1b[O".to_vec()
                }
            }
        }
    }
}

/// The launch-time result of spawning a PTY: the size the shell was
/// started at plus owning handles to read/write/kill it. Desktop wraps
/// this in a `LiveTerminalRuntime` that drives an alacritty `Term` +
/// renders into GPUI.
pub struct PreparedTerminalRuntime {
    pub size: TerminalGridSize,
    pub master: Box<dyn MasterPty + Send>,
    pub writer: Box<dyn Write + Send>,
    pub child_killer: Box<dyn ChildKiller + Send + Sync>,
    /// Broadcast tee of every byte read from the master PTY. The
    /// existing mpsc `TerminalLaunchReply::Output` path stays as-is;
    /// embedders that need remote viewers forward those output chunks
    /// through this sender after any replay bookkeeping.
    /// `send()` is non-blocking and returns Ok(subscriber_count) or
    /// Err when there are no receivers — lagged mobile subscribers
    /// just drop chunks rather than stalling the reader.
    pub output_broadcast: tokio::sync::broadcast::Sender<Vec<u8>>,
}

#[cfg(test)]
mod tests {
    use super::TerminalInputEvent;

    #[test]
    fn terminal_input_event_wraps_bracketed_paste() {
        let event = TerminalInputEvent::Paste {
            text: "hello\nworld".to_string(),
            bracketed: true,
        };

        assert_eq!(event.pty_bytes(), b"\x1b[200~hello\nworld\x1b[201~");
    }

    #[test]
    fn terminal_input_event_encodes_focus_reports() {
        let focused = TerminalInputEvent::Focus { focused: true };
        let blurred = TerminalInputEvent::Focus { focused: false };

        assert_eq!(focused.pty_bytes(), b"\x1b[I");
        assert_eq!(blurred.pty_bytes(), b"\x1b[O");
    }
}
