//! `alacritty_terminal` adapter for [`TerminalEngine`].
//!
//! Phase 0 spike: prove the trait holds. Selection / OSC 8 / search
//! are stubs — alacritty exposes them, but plumbing them through
//! the trait belongs in Phase 2 once the snapshot pipeline is
//! validated end-to-end on Linux.

use alacritty_terminal::event::VoidListener;
use alacritty_terminal::index::{Column, Line, Point};
use alacritty_terminal::term::cell::Flags as AlacFlags;
use alacritty_terminal::term::test::TermSize;
use alacritty_terminal::term::{Config, Term};
use alacritty_terminal::vte::ansi::{Color as AlacColor, CursorShape, NamedColor, Rgb};

use super::{
    cell_flags, Cell, CursorState, CursorStyle, InputEvent, SearchHit, SelectionRange,
    Snapshot, TerminalEngine,
};

/// Adapter wrapping `alacritty_terminal::Term<VoidListener>`.
///
/// `VoidListener` swallows the engine-side events (title changes,
/// PtyWrite responses, bell, …) — Phase 0 doesn't surface them.
/// Phase 2 will swap in a `crossbeam_channel`-backed listener so the
/// bridge can re-broadcast title changes and consume PtyWrite
/// responses generated by DA / DSR sequences.
pub struct AlacrittyEngine {
    term: Term<VoidListener>,
    parser: alacritty_terminal::vte::ansi::Processor,
    cols: u16,
    rows: u16,
    revision: u64,
}

impl AlacrittyEngine {
    pub fn new(cols: u16, rows: u16) -> Self {
        let cols = cols.max(2);
        let rows = rows.max(1);
        let dims = TermSize::new(cols as usize, rows as usize);
        let config = Config::default();
        let term = Term::new(config, &dims, VoidListener);
        Self {
            term,
            parser: alacritty_terminal::vte::ansi::Processor::new(),
            cols,
            rows,
            revision: 0,
        }
    }
}

impl TerminalEngine for AlacrittyEngine {
    fn write_pty(&mut self, bytes: &[u8]) {
        if bytes.is_empty() {
            return;
        }
        self.parser.advance(&mut self.term, bytes);
        self.revision = self.revision.wrapping_add(1);
    }

    fn resize(&mut self, cols: u16, rows: u16) {
        let cols = cols.max(2);
        let rows = rows.max(1);
        if cols == self.cols && rows == self.rows {
            return;
        }
        self.term
            .resize(TermSize::new(cols as usize, rows as usize));
        self.cols = cols;
        self.rows = rows;
        self.revision = self.revision.wrapping_add(1);
    }

    fn snapshot(&self, _scrollback_offset: u32, max_rows: u16) -> Snapshot {
        let cols = self.cols;
        let rows = self.rows.min(max_rows.max(1));
        let total = (cols as usize) * (rows as usize);
        let mut cells = vec![Cell::default(); total];

        let colors = self.term.colors();
        let grid = self.term.grid();

        for row in 0..rows {
            for col in 0..cols {
                let line = Line(row as i32);
                let alac_cell = &grid[Point::new(line, Column(col as usize))];
                let idx = (row as usize) * (cols as usize) + (col as usize);

                let ch = alac_cell.c as u32;
                let mut fg = resolve_color(alac_cell.fg, colors, true);
                let mut bg = resolve_color(alac_cell.bg, colors, false);

                let mut flags = 0u16;
                if alac_cell.flags.contains(AlacFlags::BOLD) {
                    flags |= cell_flags::BOLD;
                }
                if alac_cell.flags.contains(AlacFlags::ITALIC) {
                    flags |= cell_flags::ITALIC;
                }
                if alac_cell.flags.intersects(AlacFlags::ALL_UNDERLINES) {
                    flags |= cell_flags::UNDERLINE;
                }
                if alac_cell.flags.contains(AlacFlags::INVERSE) {
                    flags |= cell_flags::INVERSE;
                    std::mem::swap(&mut fg, &mut bg);
                }
                if alac_cell.flags.contains(AlacFlags::STRIKEOUT) {
                    flags |= cell_flags::STRIKETHROUGH;
                }
                if alac_cell.flags.contains(AlacFlags::DIM) {
                    flags |= cell_flags::DIM;
                }
                if alac_cell.flags.contains(AlacFlags::HIDDEN) {
                    cells[idx] = Cell {
                        ch: 0,
                        fg,
                        bg,
                        flags,
                    };
                    continue;
                }

                cells[idx] = Cell {
                    ch: if ch == ' ' as u32 { 0 } else { ch },
                    fg,
                    bg,
                    flags,
                };
            }
        }

        let cursor_point = grid.cursor.point;
        let cursor_visible = self
            .term
            .mode()
            .contains(alacritty_terminal::term::TermMode::SHOW_CURSOR);
        let cursor_shape = self.term.cursor_style().shape;

        Snapshot {
            cols,
            rows,
            cursor: CursorState {
                col: cursor_point.column.0.min(u16::MAX as usize) as u16,
                row: cursor_point.line.0.max(0).min(u16::MAX as i32) as u16,
                visible: cursor_visible,
                style: map_cursor_style(cursor_shape),
            },
            cells,
            hyperlinks: Vec::new(),
            revision: self.revision,
        }
    }

    fn encode_input(&self, event: InputEvent) -> Vec<u8> {
        match event {
            InputEvent::Char(cp) => {
                let mut buf = [0u8; 4];
                if let Some(c) = char::from_u32(cp) {
                    c.encode_utf8(&mut buf).as_bytes().to_vec()
                } else {
                    Vec::new()
                }
            }
            InputEvent::Enter => b"\r".to_vec(),
            InputEvent::Backspace => b"\x7f".to_vec(),
            InputEvent::Tab => b"\t".to_vec(),
            InputEvent::Escape => b"\x1b".to_vec(),
            InputEvent::ArrowUp => b"\x1b[A".to_vec(),
            InputEvent::ArrowDown => b"\x1b[B".to_vec(),
            InputEvent::ArrowRight => b"\x1b[C".to_vec(),
            InputEvent::ArrowLeft => b"\x1b[D".to_vec(),
            InputEvent::Resize { .. } => Vec::new(),
        }
    }

    fn selection_set(&mut self, _range: Option<SelectionRange>) {}

    fn selection_text(&self) -> Option<String> {
        None
    }

    fn hyperlink_at(&self, _col: u16, _row: u16) -> Option<String> {
        None
    }

    fn search(&self, _needle: &str) -> Vec<SearchHit> {
        Vec::new()
    }
}

fn map_cursor_style(shape: CursorShape) -> CursorStyle {
    match shape {
        CursorShape::Block | CursorShape::HollowBlock => CursorStyle::Block,
        CursorShape::Beam => CursorStyle::Bar,
        CursorShape::Underline => CursorStyle::Underline,
        CursorShape::Hidden => CursorStyle::Block,
    }
}

/// Pack RGB into 0xRRGGBBAA. Alpha = 0xFF for opaque, 0x00 for the
/// "use the theme's default background" sentinel — the Dart painter
/// treats fully-transparent bg as "skip the fill" so the canvas
/// background shows through.
fn rgb_to_rgba(rgb: Rgb, alpha: u8) -> u32 {
    ((rgb.r as u32) << 24)
        | ((rgb.g as u32) << 16)
        | ((rgb.b as u32) << 8)
        | (alpha as u32)
}

/// Resolve an alacritty `Color` to the bridge's packed RGBA. Spike
/// uses a fixed default palette — real theming is Phase 2.
fn resolve_color(
    color: AlacColor,
    overrides: &alacritty_terminal::term::color::Colors,
    is_fg: bool,
) -> u32 {
    match color {
        AlacColor::Spec(rgb) => rgb_to_rgba(rgb, 0xFF),
        AlacColor::Indexed(i) => {
            if let Some(rgb) = overrides[i as usize] {
                return rgb_to_rgba(rgb, 0xFF);
            }
            rgb_to_rgba(default_indexed(i), 0xFF)
        }
        AlacColor::Named(named) => {
            if let Some(rgb) = overrides[named] {
                return rgb_to_rgba(rgb, 0xFF);
            }
            named_default(named, is_fg)
        }
    }
}

fn named_default(named: NamedColor, is_fg: bool) -> u32 {
    match named {
        NamedColor::Background => 0x00000000,
        NamedColor::Foreground | NamedColor::DimForeground | NamedColor::BrightForeground => {
            if is_fg {
                0xEAEAEAFF
            } else {
                0x00000000
            }
        }
        NamedColor::Cursor => 0xEAEAEAFF,
        NamedColor::Black | NamedColor::DimBlack => 0x000000FF,
        NamedColor::Red | NamedColor::DimRed => 0xCC0403FF,
        NamedColor::Green | NamedColor::DimGreen => 0x19CB00FF,
        NamedColor::Yellow | NamedColor::DimYellow => 0xCECB00FF,
        NamedColor::Blue | NamedColor::DimBlue => 0x0D73CCFF,
        NamedColor::Magenta | NamedColor::DimMagenta => 0xCB1ED1FF,
        NamedColor::Cyan | NamedColor::DimCyan => 0x0DCDCDFF,
        NamedColor::White | NamedColor::DimWhite => 0xDDDDDDFF,
        NamedColor::BrightBlack => 0x767676FF,
        NamedColor::BrightRed => 0xF2201FFF,
        NamedColor::BrightGreen => 0x23FD00FF,
        NamedColor::BrightYellow => 0xFFFD00FF,
        NamedColor::BrightBlue => 0x1A8FFFFF,
        NamedColor::BrightMagenta => 0xFD28FFFF,
        NamedColor::BrightCyan => 0x14FFFFFF,
        NamedColor::BrightWhite => 0xFFFFFFFF,
    }
}

fn default_indexed(i: u8) -> Rgb {
    if i < 16 {
        let named = match i {
            0 => NamedColor::Black,
            1 => NamedColor::Red,
            2 => NamedColor::Green,
            3 => NamedColor::Yellow,
            4 => NamedColor::Blue,
            5 => NamedColor::Magenta,
            6 => NamedColor::Cyan,
            7 => NamedColor::White,
            8 => NamedColor::BrightBlack,
            9 => NamedColor::BrightRed,
            10 => NamedColor::BrightGreen,
            11 => NamedColor::BrightYellow,
            12 => NamedColor::BrightBlue,
            13 => NamedColor::BrightMagenta,
            14 => NamedColor::BrightCyan,
            _ => NamedColor::BrightWhite,
        };
        let packed = named_default(named, true);
        return Rgb {
            r: ((packed >> 24) & 0xFF) as u8,
            g: ((packed >> 16) & 0xFF) as u8,
            b: ((packed >> 8) & 0xFF) as u8,
        };
    }
    if i < 232 {
        let v = i - 16;
        let r = v / 36;
        let g = (v / 6) % 6;
        let b = v % 6;
        let scale = |c: u8| if c == 0 { 0 } else { 55 + 40 * c };
        return Rgb {
            r: scale(r),
            g: scale(g),
            b: scale(b),
        };
    }
    let v = 8 + 10 * (i - 232);
    Rgb { r: v, g: v, b: v }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_text_into_grid() {
        let mut e = AlacrittyEngine::new(20, 5);
        e.write_pty(b"hi");
        let snap = e.snapshot(0, 5);
        assert_eq!(snap.cols, 20);
        assert_eq!(snap.rows, 5);
        assert_eq!(snap.cells[0].ch, 'h' as u32);
        assert_eq!(snap.cells[1].ch, 'i' as u32);
    }

    #[test]
    fn revision_advances_on_write() {
        let mut e = AlacrittyEngine::new(10, 3);
        let r0 = e.snapshot(0, 3).revision;
        e.write_pty(b"x");
        let r1 = e.snapshot(0, 3).revision;
        assert_ne!(r0, r1);
    }

    #[test]
    fn underline_does_not_leak_after_extended_sgr() {
        // ESC[4m turns underline on, ESC[4:0m (extended "no underline")
        // should clear it. The xterm.dart bug is that 4:0 collapses
        // to 40 and underline never clears; alacritty's parser handles
        // colon sub-params correctly.
        let mut e = AlacrittyEngine::new(10, 1);
        e.write_pty(b"\x1b[4mU\x1b[4:0mx");
        let snap = e.snapshot(0, 1);
        assert!(snap.cells[0].flags & cell_flags::UNDERLINE != 0);
        assert_eq!(snap.cells[1].flags & cell_flags::UNDERLINE, 0);
    }

    #[test]
    fn resize_changes_dimensions() {
        let mut e = AlacrittyEngine::new(10, 5);
        e.resize(40, 12);
        let snap = e.snapshot(0, 12);
        assert_eq!(snap.cols, 40);
        assert_eq!(snap.rows, 12);
        assert_eq!(snap.cells.len(), 40 * 12);
    }

    #[test]
    fn encodes_basic_input() {
        let e = AlacrittyEngine::new(10, 5);
        assert_eq!(e.encode_input(InputEvent::Enter), b"\r");
        assert_eq!(e.encode_input(InputEvent::ArrowUp), b"\x1b[A");
        assert_eq!(e.encode_input(InputEvent::Char('a' as u32)), b"a");
    }
}
