// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'iroh_client.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `iroh_connect_inner`, `read_frame`, `send_frame`, `setup_tracing`, `tokio_rt`, `write_frame`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Control`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Dial a daemon's Iroh endpoint by its public `EndpointId`.
///
/// At least one of `direct_addrs` or `relay_urls` must be non-empty — the
/// sandbox has no address-lookup service, so we can't discover how to reach
/// the daemon on our own. The daemon's ticket file prints both; pass them
/// through. When both are given iroh prefers the direct path and falls
/// back to the relay if hole-punching fails (the typical mobile-cellular
/// path).
Future<IrohSession> irohConnect({
  required String endpointId,
  required List<String> directAddrs,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiIrohClientIrohConnect(
  endpointId: endpointId,
  directAddrs: directAddrs,
  relayUrls: relayUrls,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IrohSession>>
abstract class IrohSession implements RustOpaqueInterface {
  /// Closes the session. Safe to call multiple times.
  Future<void> close();

  /// Request a PTY resize on the daemon's end. Goes through the same
  /// stream as data, multiplexed by frame type.
  Future<void> resize({required int cols, required int rows});

  /// Send raw bytes to the daemon (will be written into the PTY's stdin).
  Future<void> send({required List<int> bytes});

  /// Start pushing inbound bytes into the given Dart StreamSink. Call once
  /// per session; subsequent calls return an error.
  Stream<Uint8List> subscribe();

  /// Start pushing decoded worker replies into the given Dart StreamSink.
  /// Same one-shot subscription shape as [`subscribe`]; the second call
  /// returns an error. Replies arrive in the order the daemon sent them.
  Stream<WorkerReply> subscribeWorkerReplies();

  /// Ask the daemon to watch `project_path` and start forwarding
  /// [`WorkerReply::GitRefresh`] frames for it. See
  /// `daemon-sandbox/src/frame.rs::Control::WatchProject` for the
  /// daemon-side semantics. Reissuing replaces the previous
  /// subscription.
  Future<void> watchProject({required String projectPath});
}

/// Mirror of `daemon-sandbox/src/frame.rs::PullRequestInfo`.
class PullRequestInfo {
  final BigInt number;
  final String url;
  final PullRequestState state;

  const PullRequestInfo({
    required this.number,
    required this.url,
    required this.state,
  });

  @override
  int get hashCode => number.hashCode ^ url.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PullRequestInfo &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          url == other.url &&
          state == other.state;
}

/// Mirror of `daemon-sandbox/src/frame.rs::PullRequestState`.
/// Wire form is lowercase: `"open"`, `"closed"`, `"merged"`.
enum PullRequestState { open, closed, merged }

@freezed
sealed class WorkerReply with _$WorkerReply {
  const WorkerReply._();

  /// Projection of `core::git_service::GitRefreshReply`.
  const factory WorkerReply.gitRefresh({
    required String projectId,
    String? currentBranch,
    required BigInt changedFileCount,
    required BigInt ahead,
    required BigInt behind,
  }) = WorkerReply_GitRefresh;

  /// Projection of `core::git_service::ProjectPullRequestReply`.
  /// `pr = None` → checked, no PR found (distinct from "not yet
  /// checked"). Mirror of `daemon-sandbox/src/frame.rs`.
  const factory WorkerReply.pullRequestStatus({
    required String projectId,
    required String branchName,
    PullRequestInfo? pr,
  }) = WorkerReply_PullRequestStatus;
}
