// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `iroh_connect_inner`, `setup_tracing`, `tokio_rt`

/// Dial a daemon's Iroh endpoint by its public `EndpointId`, with one or more
/// explicit direct `host:port` socket addresses.
///
/// The sandbox does not ship an address-lookup service or relay, so the
/// client needs the daemon's IP:port to dial. The daemon prints its
/// EndpointAddr on startup; pass those addresses through here.
Future<IrohSession> irohConnect({
  required String endpointId,
  required List<String> directAddrs,
}) => RustLib.instance.api.crateApiIrohClientIrohConnect(
  endpointId: endpointId,
  directAddrs: directAddrs,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IrohSession>>
abstract class IrohSession implements RustOpaqueInterface {
  /// Closes the session. Safe to call multiple times.
  Future<void> close();

  /// Send raw bytes to the daemon (will be written into the PTY's stdin).
  Future<void> send({required List<int> bytes});

  /// Start pushing inbound bytes into the given Dart StreamSink. Call once
  /// per session; subsequent calls return an error.
  Stream<Uint8List> subscribe();
}
