// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/iroh_client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiIrohClientInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1030758759;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mobile_core',
        ioDirectory: '../mobile-core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiIrohClientIrohSessionAttachTab({
    required IrohSession that,
    required String sectionId,
    required String tabId,
  });

  Future<void> crateApiIrohClientIrohSessionClose({required IrohSession that});

  Future<void> crateApiIrohClientIrohSessionDetachTab({
    required IrohSession that,
  });

  Future<void> crateApiIrohClientIrohSessionListProjects({
    required IrohSession that,
  });

  Future<void> crateApiIrohClientIrohSessionResize({
    required IrohSession that,
    required int cols,
    required int rows,
  });

  Future<void> crateApiIrohClientIrohSessionSend({
    required IrohSession that,
    required List<int> bytes,
  });

  Stream<Uint8List> crateApiIrohClientIrohSessionSubscribe({
    required IrohSession that,
  });

  Stream<WorkerReply> crateApiIrohClientIrohSessionSubscribeWorkerReplies({
    required IrohSession that,
  });

  Future<void> crateApiIrohClientIrohSessionTabResize({
    required IrohSession that,
    required int cols,
    required int rows,
  });

  Future<void> crateApiIrohClientIrohSessionWatchProject({
    required IrohSession that,
    required String projectPath,
  });

  Future<void> crateApiIrohClientInitApp();

  Future<IrohSession> crateApiIrohClientIrohConnect({
    required String endpointId,
    required List<String> directAddrs,
    required List<String> relayUrls,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_IrohSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_IrohSession;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_IrohSessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiIrohClientIrohSessionAttachTab({
    required IrohSession that,
    required String sectionId,
    required String tabId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          sse_encode_String(sectionId, serializer);
          sse_encode_String(tabId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohSessionAttachTabConstMeta,
        argValues: [that, sectionId, tabId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionAttachTabConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_attach_tab",
        argNames: ["that", "sectionId", "tabId"],
      );

  @override
  Future<void> crateApiIrohClientIrohSessionClose({required IrohSession that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIrohClientIrohSessionCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionCloseConstMeta =>
      const TaskConstMeta(debugName: "IrohSession_close", argNames: ["that"]);

  @override
  Future<void> crateApiIrohClientIrohSessionDetachTab({
    required IrohSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohSessionDetachTabConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionDetachTabConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_detach_tab",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiIrohClientIrohSessionListProjects({
    required IrohSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohSessionListProjectsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionListProjectsConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_list_projects",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiIrohClientIrohSessionResize({
    required IrohSession that,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          sse_encode_u_16(cols, serializer);
          sse_encode_u_16(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohSessionResizeConstMeta,
        argValues: [that, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionResizeConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_resize",
        argNames: ["that", "cols", "rows"],
      );

  @override
  Future<void> crateApiIrohClientIrohSessionSend({
    required IrohSession that,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohSessionSendConstMeta,
        argValues: [that, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionSendConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_send",
        argNames: ["that", "bytes"],
      );

  @override
  Stream<Uint8List> crateApiIrohClientIrohSessionSubscribe({
    required IrohSession that,
  }) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
              that,
              serializer,
            );
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiIrohClientIrohSessionSubscribeConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionSubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_subscribe",
        argNames: ["that", "sink"],
      );

  @override
  Stream<WorkerReply> crateApiIrohClientIrohSessionSubscribeWorkerReplies({
    required IrohSession that,
  }) {
    final sink = RustStreamSink<WorkerReply>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
              that,
              serializer,
            );
            sse_encode_StreamSink_worker_reply_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiIrohClientIrohSessionSubscribeWorkerRepliesConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiIrohClientIrohSessionSubscribeWorkerRepliesConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_subscribe_worker_replies",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiIrohClientIrohSessionTabResize({
    required IrohSession that,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          sse_encode_u_16(cols, serializer);
          sse_encode_u_16(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohSessionTabResizeConstMeta,
        argValues: [that, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionTabResizeConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_tab_resize",
        argNames: ["that", "cols", "rows"],
      );

  @override
  Future<void> crateApiIrohClientIrohSessionWatchProject({
    required IrohSession that,
    required String projectPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
            that,
            serializer,
          );
          sse_encode_String(projectPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohSessionWatchProjectConstMeta,
        argValues: [that, projectPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohSessionWatchProjectConstMeta =>
      const TaskConstMeta(
        debugName: "IrohSession_watch_project",
        argNames: ["that", "projectPath"],
      );

  @override
  Future<void> crateApiIrohClientInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIrohClientInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<IrohSession> crateApiIrohClientIrohConnect({
    required String endpointId,
    required List<String> directAddrs,
    required List<String> relayUrls,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(endpointId, serializer);
          sse_encode_list_String(directAddrs, serializer);
          sse_encode_list_String(relayUrls, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohConnectConstMeta,
        argValues: [endpointId, directAddrs, relayUrls],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohConnectConstMeta =>
      const TaskConstMeta(
        debugName: "iroh_connect",
        argNames: ["endpointId", "directAddrs", "relayUrls"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_IrohSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_IrohSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  IrohSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IrohSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  IrohSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IrohSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  IrohSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IrohSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<WorkerReply> dco_decode_StreamSink_worker_reply_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentProvider dco_decode_agent_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentProvider.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AgentProvider dco_decode_box_autoadd_agent_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_agent_provider(raw);
  }

  @protected
  PullRequestInfo dco_decode_box_autoadd_pull_request_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pull_request_info(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProjectSummary> dco_decode_list_project_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_project_summary).toList();
  }

  @protected
  List<TabSummary> dco_decode_list_tab_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tab_summary).toList();
  }

  @protected
  List<TaskSummary> dco_decode_list_task_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_summary).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AgentProvider? dco_decode_opt_box_autoadd_agent_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_agent_provider(raw);
  }

  @protected
  PullRequestInfo? dco_decode_opt_box_autoadd_pull_request_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pull_request_info(raw);
  }

  @protected
  ProjectKind dco_decode_project_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProjectKind.values[raw as int];
  }

  @protected
  ProjectSummary dco_decode_project_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProjectSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      kind: dco_decode_project_kind(arr[3]),
      currentBranch: dco_decode_opt_String(arr[4]),
      tasks: dco_decode_list_task_summary(arr[5]),
    );
  }

  @protected
  PullRequestInfo dco_decode_pull_request_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PullRequestInfo(
      number: dco_decode_u_64(arr[0]),
      url: dco_decode_String(arr[1]),
      state: dco_decode_pull_request_state(arr[2]),
    );
  }

  @protected
  PullRequestState dco_decode_pull_request_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PullRequestState.values[raw as int];
  }

  @protected
  TabSummary dco_decode_tab_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TabSummary(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      provider: dco_decode_opt_box_autoadd_agent_provider(arr[2]),
      running: dco_decode_bool(arr[3]),
    );
  }

  @protected
  TaskSummary dco_decode_task_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TaskSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      sectionId: dco_decode_String(arr[2]),
      branchName: dco_decode_String(arr[3]),
      activeTabId: dco_decode_String(arr[4]),
      tabs: dco_decode_list_tab_summary(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WorkerReply dco_decode_worker_reply(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return WorkerReply_GitRefresh(
          projectId: dco_decode_String(raw[1]),
          currentBranch: dco_decode_opt_String(raw[2]),
          changedFileCount: dco_decode_usize(raw[3]),
          ahead: dco_decode_usize(raw[4]),
          behind: dco_decode_usize(raw[5]),
        );
      case 1:
        return WorkerReply_PullRequestStatus(
          projectId: dco_decode_String(raw[1]),
          branchName: dco_decode_String(raw[2]),
          pr: dco_decode_opt_box_autoadd_pull_request_info(raw[3]),
        );
      case 2:
        return WorkerReply_ProjectList(
          projects: dco_decode_list_project_summary(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  IrohSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IrohSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  IrohSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IrohSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  IrohSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IrohSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<WorkerReply> sse_decode_StreamSink_worker_reply_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentProvider sse_decode_agent_provider(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AgentProvider.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AgentProvider sse_decode_box_autoadd_agent_provider(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_agent_provider(deserializer));
  }

  @protected
  PullRequestInfo sse_decode_box_autoadd_pull_request_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pull_request_info(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProjectSummary> sse_decode_list_project_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<TabSummary> sse_decode_list_tab_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TabSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tab_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<TaskSummary> sse_decode_list_task_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_summary(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AgentProvider? sse_decode_opt_box_autoadd_agent_provider(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_agent_provider(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PullRequestInfo? sse_decode_opt_box_autoadd_pull_request_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pull_request_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectKind sse_decode_project_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProjectKind.values[inner];
  }

  @protected
  ProjectSummary sse_decode_project_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_kind = sse_decode_project_kind(deserializer);
    var var_currentBranch = sse_decode_opt_String(deserializer);
    var var_tasks = sse_decode_list_task_summary(deserializer);
    return ProjectSummary(
      id: var_id,
      name: var_name,
      path: var_path,
      kind: var_kind,
      currentBranch: var_currentBranch,
      tasks: var_tasks,
    );
  }

  @protected
  PullRequestInfo sse_decode_pull_request_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_number = sse_decode_u_64(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_state = sse_decode_pull_request_state(deserializer);
    return PullRequestInfo(number: var_number, url: var_url, state: var_state);
  }

  @protected
  PullRequestState sse_decode_pull_request_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PullRequestState.values[inner];
  }

  @protected
  TabSummary sse_decode_tab_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_provider = sse_decode_opt_box_autoadd_agent_provider(deserializer);
    var var_running = sse_decode_bool(deserializer);
    return TabSummary(
      id: var_id,
      title: var_title,
      provider: var_provider,
      running: var_running,
    );
  }

  @protected
  TaskSummary sse_decode_task_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_sectionId = sse_decode_String(deserializer);
    var var_branchName = sse_decode_String(deserializer);
    var var_activeTabId = sse_decode_String(deserializer);
    var var_tabs = sse_decode_list_tab_summary(deserializer);
    return TaskSummary(
      id: var_id,
      name: var_name,
      sectionId: var_sectionId,
      branchName: var_branchName,
      activeTabId: var_activeTabId,
      tabs: var_tabs,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WorkerReply sse_decode_worker_reply(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_projectId = sse_decode_String(deserializer);
        var var_currentBranch = sse_decode_opt_String(deserializer);
        var var_changedFileCount = sse_decode_usize(deserializer);
        var var_ahead = sse_decode_usize(deserializer);
        var var_behind = sse_decode_usize(deserializer);
        return WorkerReply_GitRefresh(
          projectId: var_projectId,
          currentBranch: var_currentBranch,
          changedFileCount: var_changedFileCount,
          ahead: var_ahead,
          behind: var_behind,
        );
      case 1:
        var var_projectId = sse_decode_String(deserializer);
        var var_branchName = sse_decode_String(deserializer);
        var var_pr = sse_decode_opt_box_autoadd_pull_request_info(deserializer);
        return WorkerReply_PullRequestStatus(
          projectId: var_projectId,
          branchName: var_branchName,
          pr: var_pr,
        );
      case 2:
        var var_projects = sse_decode_list_project_summary(deserializer);
        return WorkerReply_ProjectList(projects: var_projects);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as IrohSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as IrohSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohSession(
    IrohSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as IrohSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_worker_reply_Sse(
    RustStreamSink<WorkerReply> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_worker_reply,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_provider(AgentProvider self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_agent_provider(
    AgentProvider self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_agent_provider(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pull_request_info(
    PullRequestInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pull_request_info(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_project_summary(
    List<ProjectSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tab_summary(
    List<TabSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tab_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_task_summary(
    List<TaskSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_agent_provider(
    AgentProvider? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_agent_provider(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pull_request_info(
    PullRequestInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pull_request_info(self, serializer);
    }
  }

  @protected
  void sse_encode_project_kind(ProjectKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_project_summary(
    ProjectSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_project_kind(self.kind, serializer);
    sse_encode_opt_String(self.currentBranch, serializer);
    sse_encode_list_task_summary(self.tasks, serializer);
  }

  @protected
  void sse_encode_pull_request_info(
    PullRequestInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.number, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_pull_request_state(self.state, serializer);
  }

  @protected
  void sse_encode_pull_request_state(
    PullRequestState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tab_summary(TabSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_box_autoadd_agent_provider(self.provider, serializer);
    sse_encode_bool(self.running, serializer);
  }

  @protected
  void sse_encode_task_summary(TaskSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.sectionId, serializer);
    sse_encode_String(self.branchName, serializer);
    sse_encode_String(self.activeTabId, serializer);
    sse_encode_list_tab_summary(self.tabs, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_worker_reply(WorkerReply self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case WorkerReply_GitRefresh(
        projectId: final projectId,
        currentBranch: final currentBranch,
        changedFileCount: final changedFileCount,
        ahead: final ahead,
        behind: final behind,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(projectId, serializer);
        sse_encode_opt_String(currentBranch, serializer);
        sse_encode_usize(changedFileCount, serializer);
        sse_encode_usize(ahead, serializer);
        sse_encode_usize(behind, serializer);
      case WorkerReply_PullRequestStatus(
        projectId: final projectId,
        branchName: final branchName,
        pr: final pr,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(projectId, serializer);
        sse_encode_String(branchName, serializer);
        sse_encode_opt_box_autoadd_pull_request_info(pr, serializer);
      case WorkerReply_ProjectList(projects: final projects):
        sse_encode_i_32(2, serializer);
        sse_encode_list_project_summary(projects, serializer);
    }
  }
}

@sealed
class IrohSessionImpl extends RustOpaque implements IrohSession {
  // Not to be used by end users
  IrohSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  IrohSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_IrohSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_IrohSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_IrohSessionPtr,
  );

  /// Subscribe this session to the live PTY byte stream for
  /// `(section_id, tab_id)`. The daemon will forward the attached
  /// tab's output as [`TY_DATA`] frames on the existing `subscribe`
  /// sink. At most one attachment per session — re-issuing replaces
  /// the previous one. Mirror of
  /// `daemon-sandbox/src/frame.rs::Control::AttachTab`.
  Future<void> attachTab({required String sectionId, required String tabId}) =>
      RustLib.instance.api.crateApiIrohClientIrohSessionAttachTab(
        that: this,
        sectionId: sectionId,
        tabId: tabId,
      );

  /// Closes the session. Safe to call multiple times.
  Future<void> close() =>
      RustLib.instance.api.crateApiIrohClientIrohSessionClose(that: this);

  /// Stop forwarding PTY bytes for the currently-attached tab.
  /// Idempotent if nothing is attached. Mirror of
  /// `daemon-sandbox/src/frame.rs::Control::DetachTab`.
  Future<void> detachTab() =>
      RustLib.instance.api.crateApiIrohClientIrohSessionDetachTab(that: this);

  /// Ask the daemon to send back its current project list as a
  /// [`WorkerReply::ProjectList`] frame.
  Future<void> listProjects() => RustLib.instance.api
      .crateApiIrohClientIrohSessionListProjects(that: this);

  /// Request a PTY resize on the daemon's end. Goes through the same
  /// stream as data, multiplexed by frame type.
  Future<void> resize({required int cols, required int rows}) => RustLib
      .instance
      .api
      .crateApiIrohClientIrohSessionResize(that: this, cols: cols, rows: rows);

  /// Send raw bytes to the daemon (will be written into the PTY's stdin).
  Future<void> send({required List<int> bytes}) => RustLib.instance.api
      .crateApiIrohClientIrohSessionSend(that: this, bytes: bytes);

  /// Start pushing inbound bytes into the given Dart StreamSink. Call once
  /// per session; subsequent calls return an error.
  Stream<Uint8List> subscribe() =>
      RustLib.instance.api.crateApiIrohClientIrohSessionSubscribe(that: this);

  /// Start pushing decoded worker replies into the given Dart StreamSink.
  /// Same one-shot subscription shape as [`subscribe`]; the second call
  /// returns an error. Replies arrive in the order the daemon sent them.
  Stream<WorkerReply> subscribeWorkerReplies() => RustLib.instance.api
      .crateApiIrohClientIrohSessionSubscribeWorkerReplies(that: this);

  /// Resize the currently-attached tab's PTY. Silently no-ops on
  /// the daemon when nothing is attached. Mirror of
  /// `daemon-sandbox/src/frame.rs::Control::TabResize`.
  Future<void> tabResize({required int cols, required int rows}) =>
      RustLib.instance.api.crateApiIrohClientIrohSessionTabResize(
        that: this,
        cols: cols,
        rows: rows,
      );

  /// Ask the daemon to watch `project_path` and start forwarding
  /// [`WorkerReply::GitRefresh`] frames for it. See
  /// `daemon-sandbox/src/frame.rs::Control::WatchProject` for the
  /// daemon-side semantics. Reissuing replaces the previous
  /// subscription.
  Future<void> watchProject({required String projectPath}) =>
      RustLib.instance.api.crateApiIrohClientIrohSessionWatchProject(
        that: this,
        projectPath: projectPath,
      );
}
